//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_11_l, int16_t g_12_l, int32_t g_17_l, char g_32_l, int16_t g_37_l, int32_t g_38_l, int32_t g_47_l, int32_t g_50_l, int32_t g_52_l, int32_t g_54_l, int32_t g_58_l, int32_t g_68_l, int16_t g_99_l, int16_t g_100_l, int16_t g_145_l, int32_t g_160_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1 = 1016; // 0x4e78
int64_t g2 = 0; // 0x4fe0
int32_t g3 = 3; // 0x5020
int32_t g4 = 0x2a3b; // 0x5024
int32_t g5 = 1; // 0x5028
int32_t g6 = 0x4e780001; // 0x502c
int32_t g7 = -0x6bb7b188; // 0x502e
int32_t g8 = -0x82a6bb8; // 0x5030
int32_t g9 = -0x624ddec6; // 0x5034
int32_t g10 = 1; // 0x5038
int32_t g11 = -0x68099733; // 0x503c
int32_t g12 = 0x385637ea; // 0x5040
int32_t g13 = 1; // 0x5044
int32_t g14 = 8; // 0x5048
int32_t g15 = 0x41c9d; // 0x504c
int32_t g16 = -0x17fffffc; // 0x504e
int32_t g17 = -0x2cc1800; // 0x5050
int32_t g18 = -1; // 0x5054
char g19 = 0; // 0x5060
int16_t g20 = 0; // 0x5070
int32_t * g21 = NULL; // 0x5080
int32_t g22;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g22;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return 0x5058;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (g19 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g2 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x5018);
    }
    int64_t result2 = function_1080(); // 0x1118
    g19 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s187r2.c
// Address range: 0x1150 - 0x1328
// Line range:    171 - 195
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(g3, "g_11", v1);
    transparent_crc((int32_t)*(int16_t *)&g4, "g_12", v1);
    transparent_crc(g5, "g_17", v1);
    transparent_crc((int32_t)*(char *)&g6, "g_32", v1);
    transparent_crc((int32_t)*(int16_t *)&g7, "g_37", v1);
    transparent_crc(g8, "g_38", v1);
    transparent_crc(g9, "g_47", v1);
    transparent_crc(g10, "g_50", v1);
    transparent_crc(g11, "g_52", v1);
    transparent_crc(g12, "g_54", v1);
    transparent_crc(g13, "g_58", v1);
    transparent_crc(g14, "g_68", v1);
    transparent_crc((int32_t)*(int16_t *)&g15, "g_99", v1);
    transparent_crc((int32_t)g20, "g_100", v1);
    transparent_crc((int32_t)*(int16_t *)&g16, "g_145", v1);
    transparent_crc(g17, "g_160", v1);
    platform_main_end(-1 - *(int32_t *)0x5054, v1);
    return (int32_t)&g22 ^ (int32_t)&g22;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1330 - 0x1336
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1330
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1340 - 0x13d5
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x13a9
        int32_t v2 = i; // 0x1340
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x1376
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x13b4
        *(int32_t *)(4 * i + (int64_t)&g21) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s187r2.c
// Address range: 0x13e0 - 0x1e7b
// Line range:    53 - 164
int32_t func_1(void) {
    // 0x13e0
    set_var(0x112567c8, 0x2a3b, -10, 1, (int16_t)&g1, -0x82a6bb8, -0x624ddec6, 1, -0x68099733, 0x385637ea, 1, 8, 0x1c9d, -1, 4, -0x2cc1801);
    return 181;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1e80 - 0x1ec5
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x1e80
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x1ea4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g18);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1ed0 - 0x1ef5
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x1ed0
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s187r2.c
// Address range: 0x1f00 - 0x1fe6
// Line range:    43 - 45
int32_t set_var(int32_t g_11_l, int16_t g_12_l, int32_t g_17_l, char g_32_l, int16_t g_37_l, int32_t g_38_l, int32_t g_47_l, int32_t g_50_l, int32_t g_52_l, int32_t g_54_l, int32_t g_58_l, int32_t g_68_l, int16_t g_99_l, int16_t g_100_l, int16_t g_145_l, int32_t g_160_l) {
    // 0x1f00
    g3 = g_11_l;
    *(int16_t *)&g4 = g_12_l;
    g5 = g_17_l;
    *(char *)&g6 = g_32_l;
    *(int16_t *)&g7 = g_37_l;
    g8 = g_38_l;
    g9 = g_47_l;
    g10 = g_50_l;
    g11 = g_52_l;
    g12 = g_54_l;
    g13 = g_58_l;
    g14 = g_68_l;
    *(int16_t *)&g15 = g_99_l;
    g20 = g_100_l;
    *(int16_t *)&g16 = g_145_l;
    g17 = g_160_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1ff0 - 0x204d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x1ff0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2050 - 0x2090
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g18;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g21); // 0x2085
    g18 = v1 / 256 ^ v2;
}

// Address range: 0x2090 - 0x209d
int64_t _fini(void) {
    // 0x2090
    int64_t result; // 0x2090
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

