//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_7_l, int32_t g_11_l, int32_t g_13_l, int32_t g_29_l, int16_t g_33_l, char g_51_l, int32_t g_87_l, int16_t g_101_l, int32_t g_145_l, int16_t g_147_l, int16_t g_160_l, int32_t g_162_l, int16_t g_163_l, int32_t g_181_l, int32_t g_224_l, int32_t g_225_l, int32_t g_245_l, int32_t g_269_l, char g_294_l, int16_t g_295_l, int32_t g_296_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4fe0
int32_t g2 = 0x4aa0d722; // 0x5020
int32_t g3 = 1; // 0x5024
int32_t g4 = 0x6ce4a6f4; // 0x5028
int32_t g5 = 0xab0002; // 0x502c
int32_t g6 = 0x100ab; // 0x502e
int32_t g7 = 1; // 0x5030
int16_t g8 = 0x42c0; // 0x5034
int32_t g9 = -0x670fcf09; // 0x5038
int32_t g10 = 0x4aaadee8; // 0x503c
int16_t g11 = 0x4aaa; // 0x503e
int32_t g12 = -0x5235221; // 0x5040
int32_t g13 = -0x5db57da7; // 0x5044
int32_t g14 = -9; // 0x5048
int32_t g15 = 0x5a230db6; // 0x504c
int32_t g16 = -0x63f25491; // 0x5050
char g17 = -9; // 0x5054
int32_t g18 = 0x1ffff; // 0x5056
int32_t g19 = 1; // 0x5058
int32_t g20 = -1; // 0x505c
int64_t g21 = 0; // 0x5060
int32_t g22 = 0; // 0x5070
int16_t g23 = 0; // 0x5074
int32_t g24 = 0; // 0x5078
int32_t * g25 = NULL; // 0x5080
int32_t g26;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g26;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g21;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g21 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x5018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g21 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s201r2.c
// Address range: 0x1150 - 0x139b
// Line range:    228 - 257
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(g2, "g_7", v1);
    transparent_crc(g3, "g_11", v1);
    transparent_crc(g4, "g_13", v1);
    transparent_crc(g22, "g_29", v1);
    transparent_crc((int32_t)*(int16_t *)&g5, "g_33", v1);
    transparent_crc((int32_t)*(char *)&g6, "g_51", v1);
    transparent_crc(g7, "g_87", v1);
    transparent_crc((int32_t)g8, "g_101", v1);
    transparent_crc(g9, "g_145", v1);
    transparent_crc((int32_t)*(int16_t *)&g10, "g_147", v1);
    transparent_crc((int32_t)g11, "g_160", v1);
    transparent_crc(g12, "g_162", v1);
    transparent_crc((int32_t)g23, "g_163", v1);
    transparent_crc(g24, "g_181", v1);
    transparent_crc(g13, "g_224", v1);
    transparent_crc(g14, "g_225", v1);
    transparent_crc(g15, "g_245", v1);
    transparent_crc(g16, "g_269", v1);
    transparent_crc((int32_t)g17, "g_294", v1);
    transparent_crc((int32_t)*(int16_t *)&g18, "g_295", v1);
    transparent_crc(g19, "g_296", v1);
    platform_main_end(-1 - *(int32_t *)0x505c, v1);
    return (int32_t)&g26 ^ (int32_t)&g26;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x13a0 - 0x13a6
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x13a0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x13b0 - 0x1445
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x1419
        int32_t v2 = i; // 0x13b0
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x13e6
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x1424
        *(int32_t *)(4 * i + (int64_t)&g25) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s201r2.c
// Address range: 0x1450 - 0x27c4
// Line range:    58 - 221
int32_t func_1(void) {
    // 0x1450
    set_var(0x4aa0d722, 0x4aa0d722, 0x6ce4a6f4, 0, -0x28de, -85, 1, 0x42c0, -0x670fcf09, -0x2118, 0x4aaa, -0x5235221, 0, 0, -0x5db57da7, -9, 0x5a230db6, -0x63f25491, -9, -1, 1);
    return 0x4aa0d722;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x27d0 - 0x2815
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x27d0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x27f4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g20);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x2820 - 0x2845
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2820
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s201r2.c
// Address range: 0x2850 - 0x29a1
// Line range:    48 - 50
int32_t set_var(int32_t g_7_l, int32_t g_11_l, int32_t g_13_l, int32_t g_29_l, int16_t g_33_l, char g_51_l, int32_t g_87_l, int16_t g_101_l, int32_t g_145_l, int16_t g_147_l, int16_t g_160_l, int32_t g_162_l, int16_t g_163_l, int32_t g_181_l, int32_t g_224_l, int32_t g_225_l, int32_t g_245_l, int32_t g_269_l, char g_294_l, int16_t g_295_l, int32_t g_296_l) {
    // 0x2850
    g2 = g_7_l;
    g3 = g_11_l;
    g4 = g_13_l;
    g22 = g_29_l;
    *(int16_t *)&g5 = g_33_l;
    *(char *)&g6 = g_51_l;
    g7 = g_87_l;
    g8 = g_101_l;
    g9 = g_145_l;
    *(int16_t *)&g10 = g_147_l;
    g11 = g_160_l;
    g12 = g_162_l;
    g23 = g_163_l;
    g24 = g_181_l;
    g13 = g_224_l;
    g14 = g_225_l;
    g15 = g_245_l;
    g16 = g_269_l;
    g17 = g_294_l;
    *(int16_t *)&g18 = g_295_l;
    g19 = g_296_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x29b0 - 0x2a0d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x29b0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2a10 - 0x2a50
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g20;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g25); // 0x2a45
    g20 = v1 / 256 ^ v2;
}

// Address range: 0x2a50 - 0x2a5d
int64_t _fini(void) {
    // 0x2a50
    int64_t result; // 0x2a50
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

