//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int16_t g_15_l, int32_t g_16_l, char g_17_l, int32_t g_19_l, int32_t g_29_l, int32_t g_33_l, int16_t g_66_l, int16_t g_67_l, int32_t g_97_l, int32_t g_114_l, int32_t g_115_l, int32_t g_119_l, int32_t g_120_l, int32_t g_142_l, int16_t g_147_l, char g_149_l, char g_150_l, char g_152_l, int32_t g_178_l, int16_t g_187_l, int16_t g_191_l, int32_t g_194_l, int32_t g_212_l, int32_t g_214_l, int32_t g_225_l, int16_t g_303_l, char g_305_l, char g_312_l, int16_t g_380_l, int32_t g_384_l, int32_t g_471_l, int32_t g_492_l, int16_t g_518_l, int16_t g_547_l, int32_t g_568_l, int32_t g_569_l, int16_t g_590_l, int32_t g_724_l, char g_752_l, int16_t g_782_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x7fe0
int32_t g2 = 0xffff; // 0x8020
int32_t g3 = -1; // 0x8024
int32_t g4 = 255; // 0x8028
int32_t g5 = 0x4b3f4b14; // 0x802c
int32_t g6 = -8; // 0x8030
int32_t g7 = -4; // 0x8034
int32_t g8 = 0xb77cd22; // 0x8038
int32_t g9 = 0x24f10b77; // 0x803a
int32_t g10 = 0x2fb924f1; // 0x803c
int32_t g11 = 1; // 0x8040
int32_t g12 = 1; // 0x8044
int32_t g13 = -8; // 0x8048
int32_t g14 = 1; // 0x804c
int16_t g15 = -1; // 0x8050
char g16 = 42; // 0x8052
char g17 = -1; // 0x8053
char g18 = 1; // 0x8054
int32_t g19 = -0x75c1eb41; // 0x8058
int16_t g20 = -0x1db6; // 0x805c
int32_t g21 = -0x22f95f16; // 0x8060
int32_t g22 = -0x248f4228; // 0x8064
int32_t g23 = 1; // 0x8068
int32_t g24 = -0x3b5748fa; // 0x806c
int32_t g25 = -0x10016db; // 0x8070
char g26 = -1; // 0x8072
int32_t g27 = 0x37bcfefe; // 0x8073
int32_t g28 = -0x6ac84302; // 0x8074
int16_t g29 = -0x7517; // 0x8078
int32_t g30 = 0x232f77f; // 0x807a
int32_t g31 = 0x608c0232; // 0x807c
int32_t g32 = 0x5dacdae; // 0x8080
int32_t g33 = 0x9638; // 0x8084
int32_t g34 = -0x395b3d13; // 0x8088
char g35 = -5; // 0x808c
int64_t g36; // 0x808e
int32_t g37 = -1; // 0x8090
char g38 = 0; // 0x80a0
int32_t g39 = 0; // 0x80b0
int16_t g40 = 0; // 0x80b4
int32_t g41 = 0; // 0x80b6
int32_t g42 = 0; // 0x80b8
int32_t g43 = 0; // 0x80bc
int32_t * g44 = NULL; // 0x80c0
int32_t g45;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x7fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g45;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return 0x8098;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (g38 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x8018);
    }
    int64_t result2 = function_1080(); // 0x1118
    g38 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s333retdec.c
// Address range: 0x1150 - 0x1554
// Line range:    498 - 547
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(-1, "g_13", v1);
    transparent_crc((int32_t)*(int16_t *)&g2, "g_15", v1);
    transparent_crc(g3, "g_16", v1);
    transparent_crc((int32_t)*(char *)&g4, "g_17", v1);
    transparent_crc(g5, "g_19", v1);
    transparent_crc(g6, "g_29", v1);
    transparent_crc(g7, "g_33", v1);
    transparent_crc((int32_t)*(int16_t *)&g8, "g_66", v1);
    transparent_crc((int32_t)*(int16_t *)&g9, "g_67", v1);
    transparent_crc(g10, "g_97", v1);
    transparent_crc(g39, "g_114", v1);
    transparent_crc(g11, "g_115", v1);
    transparent_crc(g12, "g_119", v1);
    transparent_crc(g13, "g_120", v1);
    transparent_crc(g14, "g_142", v1);
    transparent_crc((int32_t)g15, "g_147", v1);
    transparent_crc((int32_t)g16, "g_149", v1);
    transparent_crc((int32_t)g17, "g_150", v1);
    transparent_crc((int32_t)g18, "g_152", v1);
    transparent_crc(g19, "g_178", v1);
    transparent_crc((int32_t)g20, "g_187", v1);
    transparent_crc((int32_t)g40, "g_191", v1);
    transparent_crc(g21, "g_194", v1);
    transparent_crc(g22, "g_212", v1);
    transparent_crc(g23, "g_214", v1);
    transparent_crc(g24, "g_225", v1);
    transparent_crc((int32_t)*(int16_t *)&g25, "g_303", v1);
    transparent_crc((int32_t)g26, "g_305", v1);
    transparent_crc((int32_t)*(char *)&g27, "g_312", v1);
    transparent_crc((int32_t)*(int16_t *)&g41, "g_380", v1);
    transparent_crc(g42, "g_384", v1);
    transparent_crc(g43, "g_471", v1);
    transparent_crc(g28, "g_492", v1);
    transparent_crc((int32_t)g29, "g_518", v1);
    transparent_crc((int32_t)*(int16_t *)&g30, "g_547", v1);
    transparent_crc(g31, "g_568", v1);
    transparent_crc(g32, "g_569", v1);
    transparent_crc((int32_t)*(int16_t *)&g33, "g_590", v1);
    transparent_crc(g34, "g_724", v1);
    transparent_crc((int32_t)g35, "g_752", v1);
    transparent_crc((int32_t)*(int16_t *)0x808e, "g_782", v1);
    platform_main_end(-1 - *(int32_t *)0x8090, v1);
    return (int32_t)&g45 ^ (int32_t)&g45;
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x1560 - 0x1566
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1560
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1570 - 0x1605
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x15d9
        int32_t v2 = i; // 0x1570
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x15a6
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x15e4
        *(int32_t *)(4 * i + (int64_t)&g44) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s333retdec.c
// Address range: 0x1610 - 0x57ca
// Line range:    78 - 491
int32_t func_1(void) {
    // 0x54b4
    set_var(-0x4228, 0, -1, 0x4912, -8, -4, -0x32de, 2935, 1, 0, 1, 1, -8, 1, -1, 42, -1, 1, 0, -0x1db6, 0, -0x22f95f16, -0x248f4228, 1, -0x3b5748fa, -0x16db, -1, -1, 0, 0, 0, -0x6ac84302, -0x7517, -2177, 0x608c0232, 0x5dacdae, -0x69c8, -0x395b3d13, -5, -1);
    return 65;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x57d0 - 0x5815
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x57d0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x57f4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g37);
    }
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x5820 - 0x5845
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x5820
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s333retdec.c
// Address range: 0x5850 - 0x5ae1
// Line range:    68 - 70
int32_t set_var(int16_t g_15_l, int32_t g_16_l, char g_17_l, int32_t g_19_l, int32_t g_29_l, int32_t g_33_l, int16_t g_66_l, int16_t g_67_l, int32_t g_97_l, int32_t g_114_l, int32_t g_115_l, int32_t g_119_l, int32_t g_120_l, int32_t g_142_l, int16_t g_147_l, char g_149_l, char g_150_l, char g_152_l, int32_t g_178_l, int16_t g_187_l, int16_t g_191_l, int32_t g_194_l, int32_t g_212_l, int32_t g_214_l, int32_t g_225_l, int16_t g_303_l, char g_305_l, char g_312_l, int16_t g_380_l, int32_t g_384_l, int32_t g_471_l, int32_t g_492_l, int16_t g_518_l, int16_t g_547_l, int32_t g_568_l, int32_t g_569_l, int16_t g_590_l, int32_t g_724_l, char g_752_l, int16_t g_782_l) {
    // 0x5850
    *(int16_t *)&g2 = g_15_l;
    g3 = g_16_l;
    *(char *)&g4 = g_17_l;
    g5 = g_19_l;
    g6 = g_29_l;
    g7 = g_33_l;
    *(int16_t *)&g8 = g_66_l;
    *(int16_t *)&g9 = g_67_l;
    g10 = g_97_l;
    g39 = g_114_l;
    g11 = g_115_l;
    g12 = g_119_l;
    g13 = g_120_l;
    g14 = g_142_l;
    g15 = g_147_l;
    g16 = g_149_l;
    g17 = g_150_l;
    g18 = g_152_l;
    g19 = g_178_l;
    g20 = g_187_l;
    g40 = g_191_l;
    g21 = g_194_l;
    g22 = g_212_l;
    g23 = g_214_l;
    g24 = g_225_l;
    *(int16_t *)&g25 = g_303_l;
    g26 = g_305_l;
    *(char *)&g27 = g_312_l;
    *(int16_t *)&g41 = g_380_l;
    g42 = g_384_l;
    g43 = g_471_l;
    g28 = g_492_l;
    g29 = g_518_l;
    *(int16_t *)&g30 = g_547_l;
    g31 = g_568_l;
    g32 = g_569_l;
    *(int16_t *)&g33 = g_590_l;
    g34 = g_724_l;
    g35 = g_752_l;
    *(int16_t *)&g36 = g_782_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x5af0 - 0x5b4d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x5af0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x5b50 - 0x5b90
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g37;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g44); // 0x5b85
    g37 = v1 / 256 ^ v2;
}

// Address range: 0x5b90 - 0x5b9d
int64_t _fini(void) {
    // 0x5b90
    int64_t result; // 0x5b90
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

