//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_3_l, int32_t g_6_l, int32_t g_34_l, int16_t g_61_l, char g_73_l, int32_t g_75_l, int16_t g_76_l, char g_77_l, int32_t g_101_l, int32_t g_137_l, int32_t g_162_l, int32_t g_173_l, int32_t g_200_l, int16_t g_300_l, int32_t g_379_l, int16_t g_380_l, int32_t g_381_l, int16_t g_392_l, int16_t g_431_l, int32_t g_435_l, int32_t g_503_l, int32_t g_509_l, int32_t g_576_l, char g_577_l, int32_t g_620_l, int32_t g_636_l, int16_t g_637_l, char g_646_l, char g_647_l, int32_t g_651_l, int32_t g_652_l, char g_674_l, int32_t g_675_l, int16_t g_692_l, int32_t g_709_l, int32_t g_742_l, int32_t g_775_l, char g_847_l, int32_t g_853_l, int32_t g_856_l, char g_885_l, int16_t g_886_l, int16_t g_941_l, int32_t g_983_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x8fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x8f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x8fe7;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x8f4f); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s354r2.c
// Address range: 0x11a0 - 0x1854
// Line range:    552 - 605
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x6e8a)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x8e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x6e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x8e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x6e60), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x8ef4); // 0x125e
    transparent_crc(v5, (char *)(v2 + 0x6e64), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x8e70); // 0x1280
    transparent_crc(v6, (char *)(v2 + 0x6e68), v1);
    uint16_t v7 = *(int16_t *)(v2 + 0x8e74); // 0x12a2
    transparent_crc((int32_t)v7, (char *)(v2 + 0x6e6d), v1);
    unsigned char v8 = *(char *)(v2 + 0x8e76); // 0x12c5
    transparent_crc((int32_t)v8, (char *)(v2 + 0x6e72), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x8e78); // 0x12e8
    transparent_crc(v9, (char *)(v2 + 0x6e77), v1);
    int16_t v10 = *(int16_t *)(v2 + 0x8e7c); // 0x130a
    transparent_crc((int32_t)v10, (char *)(v2 + 0x6e7c), v1);
    unsigned char v11 = *(char *)(v2 + 0x8ef8); // 0x132d
    transparent_crc((int32_t)v11, (char *)(v2 + 0x6e81), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x8e80); // 0x1352
    transparent_crc(v12, (char *)(v2 + 0x6e86), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x8efc); // 0x1374
    transparent_crc(v13, (char *)(v2 + 0x6e8c), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x8e84); // 0x1396
    transparent_crc(v14, (char *)(v2 + 0x6e92), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x8e88); // 0x13b8
    transparent_crc(v15, (char *)(v2 + 0x6e98), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x8e8c); // 0x13da
    transparent_crc(v16, (char *)(v2 + 0x6e9e), v1);
    uint16_t v17 = *(int16_t *)(v2 + 0x8e90); // 0x13fc
    transparent_crc((int32_t)v17, (char *)(v2 + 0x6ea4), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x8e94); // 0x141f
    transparent_crc(v18, (char *)(v2 + 0x6eaa), v1);
    int16_t v19 = *(int16_t *)(v2 + 0x8f00); // 0x1441
    transparent_crc((int32_t)v19, (char *)(v2 + 0x6eb0), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x8e98); // 0x1467
    transparent_crc(v20, (char *)(v2 + 0x6eb6), v1);
    uint16_t v21 = *(int16_t *)(v2 + 0x8f02); // 0x1489
    transparent_crc((int32_t)v21, (char *)(v2 + 0x6ebc), v1);
    int16_t v22 = *(int16_t *)(v2 + 0x8e9c); // 0x14af
    transparent_crc((int32_t)v22, (char *)(v2 + 0x6ec2), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x8ea0); // 0x14d2
    transparent_crc(v23, (char *)(v2 + 0x6ec8), v1);
    int32_t v24 = *(int32_t *)(v2 + 0x8f04); // 0x14f4
    transparent_crc(v24, (char *)(v2 + 0x6ece), v1);
    int32_t v25 = *(int32_t *)(v2 + 0x8ea4); // 0x1516
    transparent_crc(v25, (char *)(v2 + 0x6ed4), v1);
    int32_t v26 = *(int32_t *)(v2 + 0x8ea8); // 0x1538
    transparent_crc(v26, (char *)(v2 + 0x6eda), v1);
    unsigned char v27 = *(char *)(v2 + 0x8f08); // 0x155a
    transparent_crc((int32_t)v27, (char *)(v2 + 0x6ee0), v1);
    int32_t v28 = *(int32_t *)(v2 + 0x8eac); // 0x157d
    transparent_crc(v28, (char *)(v2 + 0x6ee6), v1);
    int32_t v29 = *(int32_t *)(v2 + 0x8eb0); // 0x159f
    transparent_crc(v29, (char *)(v2 + 0x6eec), v1);
    int16_t v30 = *(int16_t *)(v2 + 0x8eb4); // 0x15c1
    transparent_crc((int32_t)v30, (char *)(v2 + 0x6ef2), v1);
    char v31 = *(char *)(v2 + 0x8eb6); // 0x15e4
    transparent_crc((int32_t)v31, (char *)(v2 + 0x6ef8), v1);
    unsigned char v32 = *(char *)(v2 + 0x8eb7); // 0x1609
    transparent_crc((int32_t)v32, (char *)(v2 + 0x6efe), v1);
    int32_t v33 = *(int32_t *)(v2 + 0x8eb8); // 0x162c
    transparent_crc(v33, (char *)(v2 + 0x6f04), v1);
    int32_t v34 = *(int32_t *)(v2 + 0x8ebc); // 0x164e
    transparent_crc(v34, (char *)(v2 + 0x6f0a), v1);
    char v35 = *(char *)(v2 + 0x8ec0); // 0x1670
    transparent_crc((int32_t)v35, (char *)(v2 + 0x6f10), v1);
    int32_t v36 = *(int32_t *)(v2 + 0x8ec4); // 0x1695
    transparent_crc(v36, (char *)(v2 + 0x6f16), v1);
    int16_t v37 = *(int16_t *)(v2 + 0x8ec8); // 0x16b7
    transparent_crc((int32_t)v37, (char *)(v2 + 0x6f1c), v1);
    int32_t v38 = *(int32_t *)(v2 + 0x8ecc); // 0x16da
    transparent_crc(v38, (char *)(v2 + 0x6f22), v1);
    int32_t v39 = *(int32_t *)(v2 + 0x8ed0); // 0x16fc
    transparent_crc(v39, (char *)(v2 + 0x6f28), v1);
    int32_t v40 = *(int32_t *)(v2 + 0x8ed4); // 0x171e
    transparent_crc(v40, (char *)(v2 + 0x6f2e), v1);
    unsigned char v41 = *(char *)(v2 + 0x8ed8); // 0x1740
    transparent_crc((int32_t)v41, (char *)(v2 + 0x6f34), v1);
    int32_t v42 = *(int32_t *)(v2 + 0x8edc); // 0x1765
    transparent_crc(v42, (char *)(v2 + 0x6f3a), v1);
    int32_t v43 = *(int32_t *)(v2 + 0x8ee0); // 0x1787
    transparent_crc(v43, (char *)(v2 + 0x6f40), v1);
    char v44 = *(char *)(v2 + 0x8ee4); // 0x17a9
    transparent_crc((int32_t)v44, (char *)(v2 + 0x6f46), v1);
    uint16_t v45 = *(int16_t *)(v2 + 0x8f0a); // 0x17cc
    transparent_crc((int32_t)v45, (char *)(v2 + 0x6f4c), v1);
    int16_t v46 = *(int16_t *)(v2 + 0x8ee6); // 0x17ef
    transparent_crc((int32_t)v46, (char *)(v2 + 0x6f52), v1);
    int32_t v47 = *(int32_t *)(v2 + 0x8ee8); // 0x1812
    transparent_crc(v47, (char *)(v2 + 0x6f58), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x8eec), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1860 - 0x1865
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1860
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1870 - 0x1918
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x18ea
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x18b1
        while (v1 != 0) {
            // 0x18b7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x18f5
        int32_t v5; // 0x1870
        *(int32_t *)(v5 + 0x883d + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s354r2.c
// Address range: 0x1920 - 0x70c2
// Line range:    82 - 545
int32_t func_1(void) {
    // 0x70b4
    set_var(0, 1, 0, -2, -0x3fa5, 0, -0x756c7d7f, -29, 0, -1, -11, -0x3a82831d, -3, -0x24451fc1, 0x2dfc, 28, 0, -7, 0, 1, 8, 0, 0, -0x496d8e1b, 0, -0x293bfc9, 1, 1, -1, -6, -6, -0xa5e314c, -70, 1, 0x34d8, 0x2d200bdc, 0x2064611c, -0x60f5c8f8, 8, 0x72ab03ba, -1, -4, 0, 0x7e42, 1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x70d0 - 0x712f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x70d0
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x70d0
    if (v1 != 0) {
        // 0x7104
        printf((char *)(v1 + 0x102e));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x7130 - 0x7164
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x7130
    int32_t v1; // 0x7130
    printf((char *)(v1 + 4081));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s354r2.c
// Address range: 0x7170 - 0x7417
// Line range:    72 - 74
int32_t set_var(int32_t g_2_l, int32_t g_3_l, int32_t g_6_l, int32_t g_34_l, int16_t g_61_l, char g_73_l, int32_t g_75_l, int16_t g_76_l, char g_77_l, int32_t g_101_l, int32_t g_137_l, int32_t g_162_l, int32_t g_173_l, int32_t g_200_l, int16_t g_300_l, int32_t g_379_l, int16_t g_380_l, int32_t g_381_l, int16_t g_392_l, int16_t g_431_l, int32_t g_435_l, int32_t g_503_l, int32_t g_509_l, int32_t g_576_l, char g_577_l, int32_t g_620_l, int32_t g_636_l, int16_t g_637_l, char g_646_l, char g_647_l, int32_t g_651_l, int32_t g_652_l, char g_674_l, int32_t g_675_l, int16_t g_692_l, int32_t g_709_l, int32_t g_742_l, int32_t g_775_l, char g_847_l, int32_t g_853_l, int32_t g_856_l, char g_885_l, int16_t g_886_l, int16_t g_941_l, int32_t g_983_l) {
    // 0x7170
    int32_t v1; // 0x7170
    *(int32_t *)(v1 + 0x2e9c) = g_3_l;
    *(int32_t *)(v1 + 0x2ea0) = g_6_l;
    *(int32_t *)(v1 + 0x2f28) = g_34_l;
    *(int32_t *)(v1 + 0x2ea4) = (int32_t)g_61_l;
    *(int16_t *)(v1 + 0x2ea8) = (int16_t)g_73_l;
    *(char *)(v1 + 0x2eaa) = (char)g_75_l;
    *(int32_t *)(v1 + 0x2eac) = (int32_t)g_76_l;
    *(int16_t *)(v1 + 0x2eb0) = (int16_t)g_77_l;
    *(char *)(v1 + 0x2f2c) = (char)g_101_l;
    *(int32_t *)(v1 + 0x2eb4) = g_137_l;
    *(int32_t *)(v1 + 0x2f30) = g_162_l;
    *(int32_t *)(v1 + 0x2eb8) = g_173_l;
    *(int32_t *)(v1 + 0x2ebc) = g_200_l;
    *(int32_t *)(v1 + 0x2ec0) = (int32_t)g_300_l;
    *(int16_t *)(v1 + 0x2ec4) = (int16_t)g_379_l;
    *(int32_t *)(v1 + 0x2ec8) = (int32_t)g_380_l;
    *(int16_t *)(v1 + 0x2f34) = (int16_t)g_381_l;
    *(int32_t *)(v1 + 0x2ecc) = (int32_t)g_392_l;
    *(int16_t *)(v1 + 0x2f36) = g_431_l;
    *(int16_t *)(v1 + 0x2ed0) = (int16_t)g_435_l;
    *(int32_t *)(v1 + 0x2ed4) = g_503_l;
    *(int32_t *)(v1 + 0x2f38) = g_509_l;
    *(int32_t *)(v1 + 0x2ed8) = g_576_l;
    *(int32_t *)(v1 + 0x2edc) = (int32_t)g_577_l;
    *(char *)(v1 + 0x2f3c) = (char)g_620_l;
    *(int32_t *)(v1 + 0x2ee0) = g_636_l;
    *(int32_t *)(v1 + 0x2ee4) = (int32_t)g_637_l;
    *(int16_t *)(v1 + 0x2ee8) = (int16_t)g_646_l;
    *(char *)(v1 + 0x2eea) = g_647_l;
    *(char *)(v1 + 0x2eeb) = (char)g_651_l;
    *(int32_t *)(v1 + 0x2eec) = g_652_l;
    *(int32_t *)(v1 + 0x2ef0) = (int32_t)g_674_l;
    *(char *)(v1 + 0x2ef4) = (char)g_675_l;
    *(int32_t *)(v1 + 0x2ef8) = (int32_t)g_692_l;
    *(int16_t *)(v1 + 0x2efc) = (int16_t)g_709_l;
    *(int32_t *)(v1 + 0x2f00) = g_742_l;
    *(int32_t *)(v1 + 0x2f04) = g_775_l;
    *(int32_t *)(v1 + 0x2f08) = (int32_t)g_847_l;
    *(char *)(v1 + 0x2f0c) = (char)g_853_l;
    *(int32_t *)(v1 + 0x2f10) = g_856_l;
    *(int32_t *)(v1 + 0x2f14) = (int32_t)g_885_l;
    *(char *)(v1 + 0x2f18) = (char)g_886_l;
    *(int16_t *)(v1 + 0x2f3e) = g_941_l;
    *(int16_t *)(v1 + 0x2f1a) = (int16_t)g_983_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x7420 - 0x74a0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x7420
    int32_t v1; // 0x7420
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x74a0 - 0x74e4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x74a0
    int32_t v1; // 0x74a0
    int32_t * v2 = (int32_t *)(v1 + 0x2bef); // 0x74b3
    uint32_t v3 = *v2; // 0x74b3
    char v4; // 0x74a0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2c0f + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x74e4 - 0x74fc
int32_t _fini(void) {
    // 0x74e4
    int32_t v1; // 0x74e4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

