//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_13_l, int32_t g_28_l, int32_t g_34_l, int32_t g_43_l, int32_t g_67_l, int16_t g_70_l, int32_t g_71_l, char g_76_l, int32_t g_99_l, int32_t g_120_l, int16_t g_125_l, int16_t g_137_l, int32_t g_198_l, int32_t g_230_l, int32_t g_231_l, int32_t g_278_l, int16_t g_421_l, int32_t g_432_l, int16_t g_484_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x4faf;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f17); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s380r2.c
// Address range: 0x11a0 - 0x14eb
// Line range:    384 - 412
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2ebb)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x4e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x2e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x4e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x2e60), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x4e70); // 0x125e
    transparent_crc(v5, (char *)(v2 + 0x2e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x4e74); // 0x1280
    transparent_crc(v6, (char *)(v2 + 0x2e6a), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x4e78); // 0x12a2
    transparent_crc(v7, (char *)(v2 + 0x2e6f), v1);
    int32_t v8 = *(int32_t *)(v2 + 0x4e7c); // 0x12c4
    transparent_crc(v8, (char *)(v2 + 0x2e74), v1);
    int16_t v9 = *(int16_t *)(v2 + 0x4e80); // 0x12e6
    transparent_crc((int32_t)v9, (char *)(v2 + 0x2e79), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x4e84); // 0x1309
    transparent_crc(v10, (char *)(v2 + 0x2e7e), v1);
    unsigned char v11 = *(char *)(v2 + 0x4e88); // 0x132b
    transparent_crc((int32_t)v11, (char *)(v2 + 0x2e83), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x4e8c); // 0x134e
    transparent_crc(v12, (char *)(v2 + 0x2e88), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e90); // 0x1370
    transparent_crc(v13, (char *)(v2 + 0x2e8d), v1);
    int16_t v14 = *(int16_t *)(v2 + 0x4e94); // 0x1392
    transparent_crc((int32_t)v14, (char *)(v2 + 0x2e93), v1);
    uint16_t v15 = *(int16_t *)(v2 + 0x4e96); // 0x13b5
    transparent_crc((int32_t)v15, (char *)(v2 + 0x2e99), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x4e98); // 0x13d8
    transparent_crc(v16, (char *)(v2 + 0x2e9f), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x4e9c); // 0x13fa
    transparent_crc(v17, (char *)(v2 + 0x2ea5), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x4ea0); // 0x141c
    transparent_crc(v18, (char *)(v2 + 0x2eab), v1);
    int32_t v19 = *(int32_t *)(v2 + 0x4ea4); // 0x143e
    transparent_crc(v19, (char *)(v2 + 0x2eb1), v1);
    uint16_t v20 = *(int16_t *)(v2 + 0x4ea8); // 0x1460
    transparent_crc((int32_t)v20, (char *)(v2 + 0x2eb7), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x4eac); // 0x1483
    transparent_crc(v21, (char *)(v2 + 0x2ebd), v1);
    uint16_t v22 = *(int16_t *)(v2 + 0x4eb0); // 0x14a5
    transparent_crc((int32_t)v22, (char *)(v2 + 0x2ec3), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4eb4), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x14f0 - 0x14f5
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x14f0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1500 - 0x15a8
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x157a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1541
        while (v1 != 0) {
            // 0x1547
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1585
        int32_t v5; // 0x1500
        *(int32_t *)(v5 + 0x4b5d + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s380r2.c
// Address range: 0x15b0 - 0x3b5b
// Line range:    57 - 377
int32_t func_1(void) {
    // 0x15b0
    set_var(0, -1, 12, -0x541b4241, -7, 0x659e808e, 0x48ad, 3, 2, 0, 0x9647bf5, -1, -10, -1, -0x10548a9a, -0x534a6968, 8, -0x3a82, -0x2ddd0804, -0x5fa9);
    return 2;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3b60 - 0x3bbf
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x3b60
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x3b60
    if (v1 != 0) {
        // 0x3b94
        printf((char *)(v1 + 1289));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x3bc0 - 0x3bf4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x3bc0
    int32_t v1; // 0x3bc0
    printf((char *)(v1 + 1228));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s380r2.c
// Address range: 0x3c00 - 0x3d12
// Line range:    47 - 49
int32_t set_var(int32_t g_2_l, int32_t g_13_l, int32_t g_28_l, int32_t g_34_l, int32_t g_43_l, int32_t g_67_l, int16_t g_70_l, int32_t g_71_l, char g_76_l, int32_t g_99_l, int32_t g_120_l, int16_t g_125_l, int16_t g_137_l, int32_t g_198_l, int32_t g_230_l, int32_t g_231_l, int32_t g_278_l, int16_t g_421_l, int32_t g_432_l, int16_t g_484_l) {
    // 0x3c00
    int32_t v1; // 0x3c00
    *(int32_t *)(v1 + 0x240c) = g_13_l;
    *(int32_t *)(v1 + 0x2410) = g_28_l;
    *(int32_t *)(v1 + 0x2414) = g_34_l;
    *(int32_t *)(v1 + 0x2418) = g_43_l;
    *(int32_t *)(v1 + 0x241c) = g_67_l;
    *(int32_t *)(v1 + 0x2420) = (int32_t)g_70_l;
    *(int16_t *)(v1 + 0x2424) = (int16_t)g_71_l;
    *(int32_t *)(v1 + 0x2428) = (int32_t)g_76_l;
    *(char *)(v1 + 0x242c) = (char)g_99_l;
    *(int32_t *)(v1 + 0x2430) = g_120_l;
    *(int32_t *)(v1 + 0x2434) = (int32_t)g_125_l;
    *(int16_t *)(v1 + 0x2438) = g_137_l;
    *(int16_t *)(v1 + 0x243a) = (int16_t)g_198_l;
    *(int32_t *)(v1 + 0x243c) = g_230_l;
    *(int32_t *)(v1 + 0x2440) = g_231_l;
    *(int32_t *)(v1 + 0x2444) = g_278_l;
    *(int32_t *)(v1 + 0x2448) = (int32_t)g_421_l;
    *(int16_t *)(v1 + 0x244c) = (int16_t)g_432_l;
    *(int32_t *)(v1 + 0x2450) = (int32_t)g_484_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3d20 - 0x3da0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x3d20
    int32_t v1; // 0x3d20
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3da0 - 0x3de4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x3da0
    int32_t v1; // 0x3da0
    int32_t * v2 = (int32_t *)(v1 + 0x22b7); // 0x3db3
    uint32_t v3 = *v2; // 0x3db3
    char v4; // 0x3da0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x22bf + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x3de4 - 0x3dfc
int32_t _fini(void) {
    // 0x3de4
    int32_t v1; // 0x3de4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

