//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_3_l, int32_t g_4_l, int32_t g_5_l, int32_t g_8_l, int32_t g_20_l, int16_t g_22_l, int32_t g_51_l, char g_64_l, int32_t g_67_l, int32_t g_77_l, int32_t g_78_l, int32_t g_87_l, int32_t g_93_l, int32_t g_96_l, char g_141_l, char g_171_l, int32_t g_175_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4fe0
int32_t g2 = -0x64ce6758; // 0x5020
int32_t g3 = 0x5c8094a1; // 0x5024
int32_t g4 = 6; // 0x5028
int32_t g5 = 9; // 0x502c
int32_t g6 = -1; // 0x5030
int32_t g7 = 0xfffa; // 0x5034
int32_t g8 = 1; // 0x5038
int32_t g9 = 246; // 0x503c
int32_t g10 = -6; // 0x5040
int32_t g11 = -0x18667c79; // 0x5044
int32_t g12 = 0x3d6e0afc; // 0x5048
int32_t g13 = -1; // 0x504c
int32_t g14 = 3; // 0x5050
int32_t g15 = 0x18fc; // 0x5054
char g16 = 24; // 0x5055
int32_t g17 = -7; // 0x5058
int32_t g18 = -1; // 0x505c
int64_t g19 = 0; // 0x5060
int32_t g20 = 0; // 0x5070
int32_t g21 = 0; // 0x5074
int32_t * g22 = NULL; // 0x5080
int32_t g23;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g23;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g19;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g19 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x5018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g19 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s418r2.c
// Address range: 0x1150 - 0x134f
// Line range:    204 - 230
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(g2, "g_2", v1);
    transparent_crc(g3, "g_3", v1);
    transparent_crc(g4, "g_4", v1);
    transparent_crc(g5, "g_5", v1);
    transparent_crc(g20, "g_8", v1);
    transparent_crc(g6, "g_20", v1);
    transparent_crc((int32_t)*(int16_t *)&g7, "g_22", v1);
    transparent_crc(g8, "g_51", v1);
    transparent_crc((int32_t)*(char *)&g9, "g_64", v1);
    transparent_crc(g10, "g_67", v1);
    transparent_crc(g11, "g_77", v1);
    transparent_crc(g12, "g_78", v1);
    transparent_crc(g13, "g_87", v1);
    transparent_crc(g14, "g_93", v1);
    transparent_crc(g21, "g_96", v1);
    transparent_crc((int32_t)*(char *)&g15, "g_141", v1);
    transparent_crc((int32_t)g16, "g_171", v1);
    transparent_crc(g17, "g_175", v1);
    platform_main_end(-1 - *(int32_t *)0x505c, v1);
    return (int32_t)&g23 ^ (int32_t)&g23;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1350 - 0x1356
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1350
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1360 - 0x13f5
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x13c9
        int32_t v2 = i; // 0x1360
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x1396
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x13d4
        *(int32_t *)(4 * i + (int64_t)&g22) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s418r2.c
// Address range: 0x1400 - 0x23ba
// Line range:    55 - 197
int32_t func_1(void) {
    // 0x1400
    set_var(-0x64ce6758, 0x5c8094a1, 6, 14, 1, -1, -6, 1, -10, -6, -0x18667c79, 0x3d6e0afc, -1, 3, 0, -4, 24, -7);
    return 0x5c8094a1;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x23c0 - 0x2405
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x23c0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x23e4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g18);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x2410 - 0x2435
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2410
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s418r2.c
// Address range: 0x2440 - 0x2525
// Line range:    45 - 47
int32_t set_var(int32_t g_2_l, int32_t g_3_l, int32_t g_4_l, int32_t g_5_l, int32_t g_8_l, int32_t g_20_l, int16_t g_22_l, int32_t g_51_l, char g_64_l, int32_t g_67_l, int32_t g_77_l, int32_t g_78_l, int32_t g_87_l, int32_t g_93_l, int32_t g_96_l, char g_141_l, char g_171_l, int32_t g_175_l) {
    // 0x2440
    g2 = g_2_l;
    g3 = g_3_l;
    g4 = g_4_l;
    g5 = g_5_l;
    g20 = g_8_l;
    g6 = g_20_l;
    *(int16_t *)&g7 = g_22_l;
    g8 = g_51_l;
    *(char *)&g9 = g_64_l;
    g10 = g_67_l;
    g11 = g_77_l;
    g12 = g_78_l;
    g13 = g_87_l;
    g14 = g_93_l;
    g21 = g_96_l;
    *(char *)&g15 = g_141_l;
    g16 = g_171_l;
    g17 = g_175_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2530 - 0x258d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x2530
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2590 - 0x25d0
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g18;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g22); // 0x25c5
    g18 = v1 / 256 ^ v2;
}

// Address range: 0x25d0 - 0x25dd
int64_t _fini(void) {
    // 0x25d0
    int64_t result; // 0x25d0
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

