//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_15_l, int16_t g_18_l, char g_28_l, char g_33_l, int32_t g_34_l, int16_t g_44_l, int32_t g_56_l, int32_t g_57_l, int32_t g_58_l, int16_t g_59_l, int32_t g_75_l, char g_106_l, int32_t g_108_l, char g_109_l, int16_t g_138_l, int32_t g_140_l, char g_199_l, int16_t g_247_l, int16_t g_250_l, int16_t g_251_l, int32_t g_275_l, char g_276_l, char g_277_l, int32_t g_278_l, int16_t g_303_l, int32_t g_336_l, int32_t g_352_l, int32_t g_376_l, int16_t g_393_l, int16_t g_413_l, int32_t g_417_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1 = 0xf000008; // 0x277c
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g2);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x10b0
    return v1 + 0x4fb7;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f1f); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s440r2.c
// Address range: 0x11a0 - 0x167d
// Line range:    327 - 366
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2ec7)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    char v3 = *(char *)(v2 + 0x4e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x2e5c), v1);
    uint16_t v4 = *(int16_t *)(v2 + 0x4ec4); // 0x123f
    transparent_crc((int32_t)v4, (char *)(v2 + 0x2e61), v1);
    unsigned char v5 = *(char *)(v2 + 0x4e69); // 0x1262
    transparent_crc((int32_t)v5, (char *)(v2 + 0x2e66), v1);
    char v6 = *(char *)(v2 + 0x4e6a); // 0x1285
    transparent_crc((int32_t)v6, (char *)(v2 + 0x2e6b), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x4ec8); // 0x12a8
    transparent_crc(v7, (char *)(v2 + 0x2e70), v1);
    int16_t v8 = *(int16_t *)(v2 + 0x4e6c); // 0x12ca
    transparent_crc((int32_t)v8, (char *)(v2 + 0x2e75), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x4e70); // 0x12ed
    transparent_crc(v9, (char *)(v2 + 0x2e7a), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x4e74); // 0x130f
    transparent_crc(v10, (char *)(v2 + 0x2e7f), v1);
    int32_t v11 = *(int32_t *)(v2 + 0x4e78); // 0x1331
    transparent_crc(v11, (char *)(v2 + 0x2e84), v1);
    uint16_t v12 = *(int16_t *)(v2 + 0x4ecc); // 0x1353
    transparent_crc((int32_t)v12, (char *)(v2 + 0x2e89), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e7c); // 0x1379
    transparent_crc(v13, (char *)(v2 + 0x2e8e), v1);
    char v14 = *(char *)(v2 + 0x4e80); // 0x139b
    transparent_crc((int32_t)v14, (char *)(v2 + 0x2e93), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x4e84); // 0x13c0
    transparent_crc(v15, (char *)(v2 + 0x2e99), v1);
    char v16 = *(char *)(v2 + 0x4e88); // 0x13e2
    transparent_crc((int32_t)v16, (char *)(v2 + 0x2e9f), v1);
    uint16_t v17 = *(int16_t *)(v2 + 0x4e8a); // 0x1405
    transparent_crc((int32_t)v17, (char *)(v2 + 0x2ea5), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x4e8c); // 0x142b
    transparent_crc(v18, (char *)(v2 + 0x2eab), v1);
    unsigned char v19 = *(char *)(v2 + 0x4e90); // 0x144d
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eb1), v1);
    int16_t v20 = *(int16_t *)(v2 + 0x4e92); // 0x1470
    transparent_crc((int32_t)v20, (char *)(v2 + 0x2eb7), v1);
    int16_t v21 = *(int16_t *)(v2 + 0x4e94); // 0x1493
    transparent_crc((int32_t)v21, (char *)(v2 + 0x2ebd), v1);
    uint16_t v22 = *(int16_t *)(v2 + 0x4e96); // 0x14b6
    transparent_crc((int32_t)v22, (char *)(v2 + 0x2ec3), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x4e98); // 0x14dc
    transparent_crc(v23, (char *)(v2 + 0x2ec9), v1);
    char v24 = *(char *)(v2 + 0x4e9c); // 0x14fe
    transparent_crc((int32_t)v24, (char *)(v2 + 0x2ecf), v1);
    char v25 = *(char *)(v2 + 0x4e9d); // 0x1521
    transparent_crc((int32_t)v25, (char *)(v2 + 0x2ed5), v1);
    int32_t v26 = *(int32_t *)(v2 + 0x4ea0); // 0x1544
    transparent_crc(v26, (char *)(v2 + 0x2edb), v1);
    uint16_t v27 = *(int16_t *)(v2 + 0x4ea4); // 0x1566
    transparent_crc((int32_t)v27, (char *)(v2 + 0x2ee1), v1);
    int32_t v28 = *(int32_t *)(v2 + 0x4ea8); // 0x158c
    transparent_crc(v28, (char *)(v2 + 0x2ee7), v1);
    int32_t v29 = *(int32_t *)(v2 + 0x4eac); // 0x15ae
    transparent_crc(v29, (char *)(v2 + 0x2eed), v1);
    int32_t v30 = *(int32_t *)(v2 + 0x4eb0); // 0x15d0
    transparent_crc(v30, (char *)(v2 + 0x2ef3), v1);
    uint16_t v31 = *(int16_t *)(v2 + 0x4eb4); // 0x15f2
    transparent_crc((int32_t)v31, (char *)(v2 + 0x2ef9), v1);
    int16_t v32 = *(int16_t *)(v2 + 0x4eb6); // 0x1615
    transparent_crc((int32_t)v32, (char *)(v2 + 0x2eff), v1);
    int32_t v33 = *(int32_t *)(v2 + 0x4eb8); // 0x163b
    transparent_crc(v33, (char *)(v2 + 0x2f05), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4ebc), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1680 - 0x1685
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1680
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1690 - 0x1738
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x170a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x16d1
        while (v1 != 0) {
            // 0x16d7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1715
        int32_t v5; // 0x1690
        *(int32_t *)(v5 + 0x49e1 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s440r2.c
// Address range: 0x1740 - 0x37c5
// Line range:    68 - 320
int32_t func_1(void) {
    // 0x1740
    set_var(72, 0, -110, -32, 0, -0x51d6, 0x258d3b3e, 8, 0x3f2b6367, 0, 9, 73, -0x291da462, 5, -0x7f48, -9, 0, -1, 7, -0x2159, -0x6410322, 1, 10, -0x364d7ed3, 0x5ed7, 0x69775cc2, -0x6f8afe13, -4, -0x1f52, -0x5d2c, 5);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x37d0 - 0x382f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x37d0
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x37d0
    if (v1 != 0) {
        // 0x3804
        printf((char *)(v1 + 2267));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x3830 - 0x3864
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x3830
    int32_t v1; // 0x3830
    printf((char *)(v1 + 2206));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s440r2.c
// Address range: 0x3870 - 0x3a1b
// Line range:    58 - 60
int32_t set_var(char g_15_l, int16_t g_18_l, char g_28_l, char g_33_l, int32_t g_34_l, int16_t g_44_l, int32_t g_56_l, int32_t g_57_l, int32_t g_58_l, int16_t g_59_l, int32_t g_75_l, char g_106_l, int32_t g_108_l, char g_109_l, int16_t g_138_l, int32_t g_140_l, char g_199_l, int16_t g_247_l, int16_t g_250_l, int16_t g_251_l, int32_t g_275_l, char g_276_l, char g_277_l, int32_t g_278_l, int16_t g_303_l, int32_t g_336_l, int32_t g_352_l, int32_t g_376_l, int16_t g_393_l, int16_t g_413_l, int32_t g_417_l) {
    // 0x3870
    int32_t v1; // 0x3870
    *(char *)(v1 + (int32_t)&g1 + 32) = (char)g_18_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 124) = (int16_t)g_28_l;
    *(char *)(v1 + (int32_t)&g1 + 33) = g_33_l;
    *(char *)(v1 + (int32_t)&g1 + 34) = (char)g_34_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 128) = (int32_t)g_44_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 36) = (int16_t)g_56_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 40) = g_57_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 44) = g_58_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 48) = (int32_t)g_59_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 132) = (int16_t)g_75_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 52) = (int32_t)g_106_l;
    *(char *)(v1 + (int32_t)&g1 + 56) = (char)g_108_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 60) = (int32_t)g_109_l;
    *(char *)(v1 + (int32_t)&g1 + 64) = (char)g_138_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 66) = (int16_t)g_140_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 68) = (int32_t)g_199_l;
    *(char *)(v1 + (int32_t)&g1 + 72) = (char)g_247_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 74) = g_250_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 76) = g_251_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 78) = (int16_t)g_275_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 80) = (int32_t)g_276_l;
    *(char *)(v1 + (int32_t)&g1 + 84) = g_277_l;
    *(char *)(v1 + (int32_t)&g1 + 85) = (char)g_278_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 88) = (int32_t)g_303_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 92) = (int16_t)g_336_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 96) = g_352_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 100) = g_376_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 104) = (int32_t)g_393_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 108) = g_413_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 110) = (int16_t)g_417_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3a20 - 0x3aa0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x3a20
    int32_t v1; // 0x3a20
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3aa0 - 0x3ae4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x3aa0
    int32_t v1; // 0x3aa0
    int32_t * v2 = (int32_t *)(v1 + 0x25bf); // 0x3ab3
    uint32_t v3 = *v2; // 0x3ab3
    char v4; // 0x3aa0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x25d3 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x3ae4 - 0x3afc
int32_t _fini(void) {
    // 0x3ae4
    int32_t v1; // 0x3ae4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

