//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_2_l, int32_t g_12_l, char g_14_l, int32_t g_17_l, int32_t g_18_l, char g_28_l, char g_33_l, char g_35_l, int16_t g_64_l, int32_t g_78_l, int32_t g_79_l, char g_83_l, char g_84_l, char g_88_l, int32_t g_99_l, char g_102_l, int16_t g_103_l, int32_t g_113_l, int32_t g_114_l, char g_116_l, int32_t g_149_l, int32_t g_161_l, int32_t g_182_l, int32_t g_200_l, char g_225_l, char g_257_l, int16_t g_282_l, int32_t g_284_l, int32_t g_294_l, int32_t g_315_l, char g_348_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x4fbb;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f23); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s444r2.c
// Address range: 0x11a0 - 0x166c
// Line range:    355 - 394
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2ece)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    unsigned char v3 = *(char *)(v2 + 0x4e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x2e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x4e6c); // 0x123f
    transparent_crc(v4, (char *)(v2 + 0x2e60), v1);
    unsigned char v5 = *(char *)(v2 + 0x4e70); // 0x1261
    transparent_crc((int32_t)v5, (char *)(v2 + 0x2e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x4e74); // 0x1284
    transparent_crc(v6, (char *)(v2 + 0x2e6a), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x4e78); // 0x12a6
    transparent_crc(v7, (char *)(v2 + 0x2e6f), v1);
    unsigned char v8 = *(char *)(v2 + 0x4e7c); // 0x12c8
    transparent_crc((int32_t)v8, (char *)(v2 + 0x2e74), v1);
    char v9 = *(char *)(v2 + 0x4e7d); // 0x12eb
    transparent_crc((int32_t)v9, (char *)(v2 + 0x2e79), v1);
    char v10 = *(char *)(v2 + 0x4e7e); // 0x130e
    transparent_crc((int32_t)v10, (char *)(v2 + 0x2e7e), v1);
    uint16_t v11 = *(int16_t *)(v2 + 0x4e80); // 0x1331
    transparent_crc((int32_t)v11, (char *)(v2 + 0x2e83), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x4e84); // 0x1354
    transparent_crc(v12, (char *)(v2 + 0x2e88), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e88); // 0x1376
    transparent_crc(v13, (char *)(v2 + 0x2e8d), v1);
    char v14 = *(char *)(v2 + 0x4e8c); // 0x1398
    transparent_crc((int32_t)v14, (char *)(v2 + 0x2e92), v1);
    char v15 = *(char *)(v2 + 0x4e8d); // 0x13bb
    transparent_crc((int32_t)v15, (char *)(v2 + 0x2e97), v1);
    unsigned char v16 = *(char *)(v2 + 0x4e8e); // 0x13de
    transparent_crc((int32_t)v16, (char *)(v2 + 0x2e9c), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x4e90); // 0x1403
    transparent_crc(v17, (char *)(v2 + 0x2ea1), v1);
    char v18 = *(char *)(v2 + 0x4e94); // 0x1425
    transparent_crc((int32_t)v18, (char *)(v2 + 0x2ea6), v1);
    uint16_t v19 = *(int16_t *)(v2 + 0x4e96); // 0x1448
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eac), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x4e98); // 0x146b
    transparent_crc(v20, (char *)(v2 + 0x2eb2), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x4ec8); // 0x148d
    transparent_crc(v21, (char *)(v2 + 0x2eb8), v1);
    unsigned char v22 = *(char *)(v2 + 0x4e9c); // 0x14af
    transparent_crc((int32_t)v22, (char *)(v2 + 0x2ebe), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x4ea0); // 0x14d2
    transparent_crc(v23, (char *)(v2 + 0x2ec4), v1);
    int32_t v24 = *(int32_t *)(v2 + 0x4ea4); // 0x14f4
    transparent_crc(v24, (char *)(v2 + 0x2eca), v1);
    int32_t v25 = *(int32_t *)(v2 + 0x4ea8); // 0x1516
    transparent_crc(v25, (char *)(v2 + 0x2ed0), v1);
    int32_t v26 = *(int32_t *)(v2 + 0x4ecc); // 0x1538
    transparent_crc(v26, (char *)(v2 + 0x2ed6), v1);
    unsigned char v27 = *(char *)(v2 + 0x4eac); // 0x155a
    transparent_crc((int32_t)v27, (char *)(v2 + 0x2edc), v1);
    char v28 = *(char *)(v2 + 0x4ead); // 0x157d
    transparent_crc((int32_t)v28, (char *)(v2 + 0x2ee2), v1);
    uint16_t v29 = *(int16_t *)(v2 + 0x4eae); // 0x15a0
    transparent_crc((int32_t)v29, (char *)(v2 + 0x2ee8), v1);
    int32_t v30 = *(int32_t *)(v2 + 0x4eb0); // 0x15c3
    transparent_crc(v30, (char *)(v2 + 0x2eee), v1);
    int32_t v31 = *(int32_t *)(v2 + 0x4eb4); // 0x15e5
    transparent_crc(v31, (char *)(v2 + 0x2ef4), v1);
    int32_t v32 = *(int32_t *)(v2 + 0x4eb8); // 0x1607
    transparent_crc(v32, (char *)(v2 + 0x2efa), v1);
    unsigned char v33 = *(char *)(v2 + 0x4ebc); // 0x1629
    transparent_crc((int32_t)v33, (char *)(v2 + 0x2f00), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4ec0), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1670 - 0x1675
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1670
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1680 - 0x1728
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x16fa
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x16c1
        while (v1 != 0) {
            // 0x16c7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1705
        int32_t v5; // 0x1680
        *(int32_t *)(v5 + 0x49f1 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s444r2.c
// Address range: 0x1730 - 0x31e9
// Line range:    68 - 347
int32_t func_1(void) {
    // 0x2fa0
    set_var(36, -1, 30, -0x4a6ff731, 0, 23, 71, -13, -0x2983, 0x7a7cd71d, -4, 1, -7, 2, -0x3b58fe5c, 2, 0x12ed, 0, 0, 15, 1, 8, -0x4f1a1d22, 0, 1, 24, -10, -0x352c9449, 0x76b03f70, -0x255dc977, -10);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x31f0 - 0x324f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x31f0
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x31f0
    if (v1 != 0) {
        // 0x3224
        printf((char *)(v1 + 3766));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x3250 - 0x3284
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x3250
    int32_t v1; // 0x3250
    printf((char *)(v1 + 3705));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s444r2.c
// Address range: 0x3290 - 0x3426
// Line range:    58 - 60
int32_t set_var(char g_2_l, int32_t g_12_l, char g_14_l, int32_t g_17_l, int32_t g_18_l, char g_28_l, char g_33_l, char g_35_l, int16_t g_64_l, int32_t g_78_l, int32_t g_79_l, char g_83_l, char g_84_l, char g_88_l, int32_t g_99_l, char g_102_l, int16_t g_103_l, int32_t g_113_l, int32_t g_114_l, char g_116_l, int32_t g_149_l, int32_t g_161_l, int32_t g_182_l, int32_t g_200_l, char g_225_l, char g_257_l, int16_t g_282_l, int32_t g_284_l, int32_t g_294_l, int32_t g_315_l, char g_348_l) {
    // 0x3290
    int32_t v1; // 0x3290
    *(char *)(v1 + 0x2d7c) = (char)g_12_l;
    *(int32_t *)(v1 + 0x2d80) = (int32_t)g_14_l;
    *(char *)(v1 + 0x2d84) = (char)g_17_l;
    *(int32_t *)(v1 + 0x2d88) = g_18_l;
    *(int32_t *)(v1 + 0x2d8c) = (int32_t)g_28_l;
    *(char *)(v1 + 0x2d90) = g_33_l;
    *(char *)(v1 + 0x2d91) = g_35_l;
    *(char *)(v1 + 0x2d92) = (char)g_64_l;
    *(int16_t *)(v1 + 0x2d94) = (int16_t)g_78_l;
    *(int32_t *)(v1 + 0x2d98) = g_79_l;
    *(int32_t *)(v1 + 0x2d9c) = (int32_t)g_83_l;
    *(char *)(v1 + 0x2da0) = g_84_l;
    *(char *)(v1 + 0x2da1) = g_88_l;
    *(char *)(v1 + 0x2da2) = (char)g_99_l;
    *(int32_t *)(v1 + 0x2da4) = (int32_t)g_102_l;
    *(char *)(v1 + 0x2da8) = (char)g_103_l;
    *(int16_t *)(v1 + 0x2daa) = (int16_t)g_113_l;
    *(int32_t *)(v1 + 0x2dac) = g_114_l;
    *(int32_t *)(v1 + 0x2ddc) = (int32_t)g_116_l;
    *(char *)(v1 + 0x2db0) = (char)g_149_l;
    *(int32_t *)(v1 + 0x2db4) = g_161_l;
    *(int32_t *)(v1 + 0x2db8) = g_182_l;
    *(int32_t *)(v1 + 0x2dbc) = g_200_l;
    *(int32_t *)(v1 + 0x2de0) = (int32_t)g_225_l;
    *(char *)(v1 + 0x2dc0) = g_257_l;
    *(char *)(v1 + 0x2dc1) = (char)g_282_l;
    *(int16_t *)(v1 + 0x2dc2) = (int16_t)g_284_l;
    *(int32_t *)(v1 + 0x2dc4) = g_294_l;
    *(int32_t *)(v1 + 0x2dc8) = g_315_l;
    *(int32_t *)(v1 + 0x2dcc) = (int32_t)g_348_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3430 - 0x34b0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x3430
    int32_t v1; // 0x3430
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x34b0 - 0x34f4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x34b0
    int32_t v1; // 0x34b0
    int32_t * v2 = (int32_t *)(v1 + 0x2bb3); // 0x34c3
    uint32_t v3 = *v2; // 0x34c3
    char v4; // 0x34b0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2bc3 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x34f4 - 0x350c
int32_t _fini(void) {
    // 0x34f4
    int32_t v1; // 0x34f4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

