//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int16_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_2_l, int32_t g_3_l, int32_t g_4_l, int32_t g_7_l, int32_t g_10_l, int32_t g_11_l, int32_t g_20_l, int32_t g_27_l, int32_t g_28_l, int16_t g_32_l, int32_t g_34_l, char g_82_l, int32_t g_87_l, int16_t g_104_l, int32_t g_143_l, int16_t g_152_l, int32_t g_214_l, int32_t g_216_l, int32_t g_228_l, int32_t g_270_l, int32_t g_273_l, char g_274_l, int32_t g_285_l, int16_t g_286_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x3fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x3f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x3fbb;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x3f23); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s502retdec.c
// Address range: 0x11a0 - 0x1573
// Line range:    266 - 298
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x1e74)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    unsigned char v3 = *(char *)(v2 + 0x3e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x1e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x3e6c); // 0x123f
    transparent_crc(v4, (char *)(v2 + 0x1e60), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x3e70); // 0x1261
    transparent_crc(v5, (char *)(v2 + 0x1e64), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x3e74); // 0x1283
    transparent_crc(v6, (char *)(v2 + 0x1e68), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x3e78); // 0x12a5
    transparent_crc(v7, (char *)(v2 + 0x1e6c), v1);
    int32_t v8 = *(int32_t *)(v2 + 0x3e7c); // 0x12c7
    transparent_crc(v8, (char *)(v2 + 0x1e71), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x3e80); // 0x12e9
    transparent_crc(v9, (char *)(v2 + 0x1e76), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x3e84); // 0x130b
    transparent_crc(v10, (char *)(v2 + 0x1e7b), v1);
    int32_t v11 = *(int32_t *)(v2 + 0x3e88); // 0x132d
    transparent_crc(v11, (char *)(v2 + 0x1e80), v1);
    int16_t v12 = *(int16_t *)(v2 + 0x3e8c); // 0x134f
    transparent_crc((int32_t)v12, (char *)(v2 + 0x1e85), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x3e90); // 0x1372
    transparent_crc(v13, (char *)(v2 + 0x1e8a), v1);
    unsigned char v14 = *(char *)(v2 + 0x3e94); // 0x1394
    transparent_crc((int32_t)v14, (char *)(v2 + 0x1e8f), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x3e98); // 0x13b7
    transparent_crc(v15, (char *)(v2 + 0x1e94), v1);
    uint16_t v16 = *(int16_t *)(v2 + 0x3e9c); // 0x13d9
    transparent_crc((int32_t)v16, (char *)(v2 + 0x1e99), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x3ea0); // 0x13fc
    transparent_crc(v17, (char *)(v2 + 0x1e9f), v1);
    int16_t v18 = *(int16_t *)(v2 + 0x3ea4); // 0x141e
    transparent_crc((int32_t)v18, (char *)(v2 + 0x1ea5), v1);
    int32_t v19 = *(int32_t *)(v2 + 0x3ea8); // 0x1441
    transparent_crc(v19, (char *)(v2 + 0x1eab), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x3eac); // 0x1463
    transparent_crc(v20, (char *)(v2 + 0x1eb1), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x3eb0); // 0x1485
    transparent_crc(v21, (char *)(v2 + 0x1eb7), v1);
    int32_t v22 = *(int32_t *)(v2 + 0x3eb4); // 0x14a7
    transparent_crc(v22, (char *)(v2 + 0x1ebd), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x3eb8); // 0x14c9
    transparent_crc(v23, (char *)(v2 + 0x1ec3), v1);
    unsigned char v24 = *(char *)(v2 + 0x3ebc); // 0x14eb
    transparent_crc((int32_t)v24, (char *)(v2 + 0x1ec9), v1);
    int32_t v25 = *(int32_t *)(v2 + 0x3ec8); // 0x150e
    transparent_crc(v25, (char *)(v2 + 0x1ecf), v1);
    uint16_t v26 = *(int16_t *)(v2 + 0x3ebe); // 0x1530
    transparent_crc((int32_t)v26, (char *)(v2 + 0x1ed5), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x3ec0), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1580 - 0x1585
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1580
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1590 - 0x1638
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x160a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x15d1
        while (v1 != 0) {
            // 0x15d7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1615
        int32_t v5; // 0x1590
        *(int32_t *)(v5 + 0x3add + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s502retdec.c
// Address range: 0x1640 - 0x2935
// Line range:    61 - 259
int16_t func_1(void) {
    // 0x2926
    set_var(85, 0, 0, 0x417be187, 1, 0, -0x72df4af1, 0x5a165f5c, 0x783518f, -534, -0x557c04f, -8, 0x473cb3f0, -0x2b9f, -2, 0x4d42, -0x496a9b08, 2, -0x3e017ce3, -0x36924479, 4, -8, 0, 2);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2940 - 0x299f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2940
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2940
    if (v1 != 0) {
        // 0x2974
        printf((char *)(v1 + 1851));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x29a0 - 0x29d4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x29a0
    int32_t v1; // 0x29a0
    printf((char *)(v1 + 1790));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s502retdec.c
// Address range: 0x29e0 - 0x2b1f
// Line range:    51 - 53
int32_t set_var(char g_2_l, int32_t g_3_l, int32_t g_4_l, int32_t g_7_l, int32_t g_10_l, int32_t g_11_l, int32_t g_20_l, int32_t g_27_l, int32_t g_28_l, int16_t g_32_l, int32_t g_34_l, char g_82_l, int32_t g_87_l, int16_t g_104_l, int32_t g_143_l, int16_t g_152_l, int32_t g_214_l, int32_t g_216_l, int32_t g_228_l, int32_t g_270_l, int32_t g_273_l, char g_274_l, int32_t g_285_l, int16_t g_286_l) {
    // 0x29e0
    int32_t v1; // 0x29e0
    *(char *)(v1 + 0x262c) = (char)g_3_l;
    *(int32_t *)(v1 + 0x2630) = g_4_l;
    *(int32_t *)(v1 + 0x2634) = g_7_l;
    *(int32_t *)(v1 + 0x2638) = g_10_l;
    *(int32_t *)(v1 + 0x263c) = g_11_l;
    *(int32_t *)(v1 + 0x2640) = g_20_l;
    *(int32_t *)(v1 + 0x2644) = g_27_l;
    *(int32_t *)(v1 + 0x2648) = g_28_l;
    *(int32_t *)(v1 + 0x264c) = (int32_t)g_32_l;
    *(int16_t *)(v1 + 0x2650) = (int16_t)g_34_l;
    *(int32_t *)(v1 + 0x2654) = (int32_t)g_82_l;
    *(char *)(v1 + 0x2658) = (char)g_87_l;
    *(int32_t *)(v1 + 0x265c) = (int32_t)g_104_l;
    *(int16_t *)(v1 + 0x2660) = (int16_t)g_143_l;
    *(int32_t *)(v1 + 0x2664) = (int32_t)g_152_l;
    *(int16_t *)(v1 + 0x2668) = (int16_t)g_214_l;
    *(int32_t *)(v1 + 0x266c) = g_216_l;
    *(int32_t *)(v1 + 0x2670) = g_228_l;
    *(int32_t *)(v1 + 0x2674) = g_270_l;
    *(int32_t *)(v1 + 0x2678) = g_273_l;
    *(int32_t *)(v1 + 0x267c) = (int32_t)g_274_l;
    *(char *)(v1 + 0x2680) = (char)g_285_l;
    *(int32_t *)(v1 + 0x268c) = (int32_t)g_286_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2b20 - 0x2ba0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x2b20
    int32_t v1; // 0x2b20
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2ba0 - 0x2be4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x2ba0
    int32_t v1; // 0x2ba0
    int32_t * v2 = (int32_t *)(v1 + 0x24c3); // 0x2bb3
    uint32_t v3 = *v2; // 0x2bb3
    char v4; // 0x2ba0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x24cf + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x2be4 - 0x2bfc
int32_t _fini(void) {
    // 0x2be4
    int32_t v1; // 0x2be4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

