//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_5_l, int16_t g_21_l, int16_t g_22_l, int32_t g_28_l, int32_t g_41_l, char g_42_l, int32_t g_49_l, int16_t g_63_l, int32_t g_69_l, int32_t g_75_l, int32_t g_98_l, int32_t g_99_l, int32_t g_102_l, int16_t g_209_l, int32_t g_214_l, int32_t g_215_l, int32_t g_270_l, int32_t g_289_l, char g_290_l, char g_306_l, int32_t g_307_l, int32_t g_316_l, int32_t g_317_l, int32_t g_318_l, int32_t g_327_l, int16_t g_328_l, int16_t g_401_l, int16_t g_402_l, int16_t g_455_l, int16_t g_487_l, char g_505_l, int16_t g_518_l, int32_t g_549_l, char g_562_l, char g_754_l, char g_755_l, int32_t g_813_l, char g_815_l, int16_t g_816_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x8fe0
int32_t g2 = -0xff71; // 0x9020
int32_t g3 = -0x1ee60001; // 0x9022
int16_t g4 = -0x1ee7; // 0x9024
int32_t g5 = -0x31219595; // 0x9028
int32_t g6 = 219; // 0x902c
int32_t g7 = -1; // 0x9030
int32_t g8 = 0x81fb; // 0x9034
int32_t g9 = 0x2d1e5678; // 0x9038
int32_t g10 = 1; // 0x903c
int32_t g11 = -0x4830e8f4; // 0x9040
int32_t g12 = 0x681d0925; // 0x9044
int32_t g13 = 0x28aa; // 0x9048
int32_t g14 = -0x2476fde8; // 0x904c
int32_t g15 = 1; // 0x9050
int32_t g16 = -0x69a1cb83; // 0x9054
int32_t g17 = -1; // 0x9058
int32_t g18 = 0xff8a; // 0x905c
int32_t g19 = 0x230000ff; // 0x905d
int32_t g20 = 0x12f7a823; // 0x9060
int32_t g21 = -4; // 0x9064
int32_t g22 = -0x7a818f3b; // 0x9068
int32_t g23 = -0x36623aed; // 0x906c
int16_t g24 = -1; // 0x9070
int32_t g25 = -0x2a55; // 0x9072
int16_t g26 = -1; // 0x9074
int32_t g27 = -0xcbcfffa; // 0x9076
int32_t g28 = 0x8f343; // 0x9078
char g29 = 8; // 0x907a
int16_t g30 = -1; // 0x907c
int32_t g31 = -1; // 0x9080
char g32 = -96; // 0x9084
int32_t g33 = -0x40f4d5fc; // 0x9085
int32_t g34 = 0x48bf0b2a; // 0x9086
int32_t g35 = 0x48bf0b; // 0x9087
int32_t g36 = 0x48bf; // 0x9088
int32_t g37 = -1; // 0x908c
int64_t g38 = 0; // 0x9090
int32_t g39 = 0; // 0x90a0
int32_t g40 = 0; // 0x90a4
int32_t g41 = 0; // 0x90a8
int32_t g42 = 0; // 0x90ac
int32_t * g43 = NULL; // 0x90b0
int32_t g44;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x8fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g44;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g38;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g38 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x9018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g38 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s505retdec.c
// Address range: 0x1150 - 0x1526
// Line range:    607 - 654
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)&g2, "g_5", v1);
    transparent_crc((int32_t)*(int16_t *)&g3, "g_21", v1);
    transparent_crc((int32_t)g4, "g_22", v1);
    transparent_crc(g39, "g_28", v1);
    transparent_crc(g5, "g_41", v1);
    transparent_crc((int32_t)*(char *)&g6, "g_42", v1);
    transparent_crc(g7, "g_49", v1);
    transparent_crc((int32_t)*(int16_t *)&g8, "g_63", v1);
    transparent_crc(g9, "g_69", v1);
    transparent_crc(g40, "g_75", v1);
    transparent_crc(g10, "g_98", v1);
    transparent_crc(g11, "g_99", v1);
    transparent_crc(g12, "g_102", v1);
    transparent_crc((int32_t)*(int16_t *)&g13, "g_209", v1);
    transparent_crc(g14, "g_214", v1);
    transparent_crc(g15, "g_215", v1);
    transparent_crc(g16, "g_270", v1);
    transparent_crc(g17, "g_289", v1);
    transparent_crc((int32_t)*(char *)&g18, "g_290", v1);
    transparent_crc((int32_t)*(char *)&g19, "g_306", v1);
    transparent_crc(g20, "g_307", v1);
    transparent_crc(g41, "g_316", v1);
    transparent_crc(g21, "g_317", v1);
    transparent_crc(g22, "g_318", v1);
    transparent_crc(g23, "g_327", v1);
    transparent_crc((int32_t)g24, "g_328", v1);
    transparent_crc((int32_t)*(int16_t *)&g25, "g_401", v1);
    transparent_crc((int32_t)g26, "g_402", v1);
    transparent_crc((int32_t)*(int16_t *)&g27, "g_455", v1);
    transparent_crc((int32_t)*(int16_t *)&g28, "g_487", v1);
    transparent_crc((int32_t)g29, "g_505", v1);
    transparent_crc((int32_t)g30, "g_518", v1);
    transparent_crc(g31, "g_549", v1);
    transparent_crc((int32_t)g32, "g_562", v1);
    transparent_crc((int32_t)*(char *)&g33, "g_754", v1);
    transparent_crc((int32_t)*(char *)&g34, "g_755", v1);
    transparent_crc(g42, "g_813", v1);
    transparent_crc((int32_t)*(char *)&g35, "g_815", v1);
    transparent_crc((int32_t)*(int16_t *)&g36, "g_816", v1);
    platform_main_end(-1 - *(int32_t *)0x908c, v1);
    return (int32_t)&g44 ^ (int32_t)&g44;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1530 - 0x1536
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1530
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1540 - 0x15d5
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x15a9
        int32_t v2 = i; // 0x1540
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x1576
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x15b4
        *(int32_t *)(4 * i + (int64_t)&g43) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s505retdec.c
// Address range: 0x15e0 - 0x5d9d
// Line range:    76 - 600
int32_t func_1(void) {
    // 0x15e0
    set_var(112, 112, 1, 0, -0x31219595, -37, 1, 1, 0x2d1e5678, 1, 0, -1, 0x681d0925, 0x28aa, -0x2476fde8, 1, -0x69a1cb83, -1, -118, -1, 0x12f7a823, 0, -4, -0x7a818f3b, -0x36623aed, -1, -0x2a55, -1, 6, -3261, 8, -1, -1, -96, 4, 42, 0, 11, 0x48bf);
    return 0x28aa;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x5da0 - 0x5de5
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x5da0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x5dc4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g37);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x5df0 - 0x5e15
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x5df0
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s505retdec.c
// Address range: 0x5e20 - 0x60b5
// Line range:    66 - 68
int32_t set_var(char g_5_l, int16_t g_21_l, int16_t g_22_l, int32_t g_28_l, int32_t g_41_l, char g_42_l, int32_t g_49_l, int16_t g_63_l, int32_t g_69_l, int32_t g_75_l, int32_t g_98_l, int32_t g_99_l, int32_t g_102_l, int16_t g_209_l, int32_t g_214_l, int32_t g_215_l, int32_t g_270_l, int32_t g_289_l, char g_290_l, char g_306_l, int32_t g_307_l, int32_t g_316_l, int32_t g_317_l, int32_t g_318_l, int32_t g_327_l, int16_t g_328_l, int16_t g_401_l, int16_t g_402_l, int16_t g_455_l, int16_t g_487_l, char g_505_l, int16_t g_518_l, int32_t g_549_l, char g_562_l, char g_754_l, char g_755_l, int32_t g_813_l, char g_815_l, int16_t g_816_l) {
    // 0x5e20
    *(char *)&g2 = g_5_l;
    *(int16_t *)&g3 = g_21_l;
    g4 = g_22_l;
    g39 = g_28_l;
    g5 = g_41_l;
    *(char *)&g6 = g_42_l;
    g7 = g_49_l;
    *(int16_t *)&g8 = g_63_l;
    g9 = g_69_l;
    g40 = g_75_l;
    g10 = g_98_l;
    g11 = g_99_l;
    g12 = g_102_l;
    *(int16_t *)&g13 = g_209_l;
    g14 = g_214_l;
    g15 = g_215_l;
    g16 = g_270_l;
    g17 = g_289_l;
    *(char *)&g18 = g_290_l;
    *(char *)&g19 = g_306_l;
    g20 = g_307_l;
    g41 = g_316_l;
    g21 = g_317_l;
    g22 = g_318_l;
    g23 = g_327_l;
    g24 = g_328_l;
    *(int16_t *)&g25 = g_401_l;
    g26 = g_402_l;
    *(int16_t *)&g27 = g_455_l;
    *(int16_t *)&g28 = g_487_l;
    g29 = g_505_l;
    g30 = g_518_l;
    g31 = g_549_l;
    g32 = g_562_l;
    *(char *)&g33 = g_754_l;
    *(char *)&g34 = g_755_l;
    g42 = g_813_l;
    *(char *)&g35 = g_815_l;
    *(int16_t *)&g36 = g_816_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x60c0 - 0x611d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x60c0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x6120 - 0x6160
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g37;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g43); // 0x6155
    g37 = v1 / 256 ^ v2;
}

// Address range: 0x6160 - 0x616d
int64_t _fini(void) {
    // 0x6160
    int64_t result; // 0x6160
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

