//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int16_t g_10_l, char g_11_l, int32_t g_30_l, int32_t g_38_l, int32_t g_53_l, char g_56_l, int32_t g_74_l, char g_80_l, int16_t g_81_l, int16_t g_89_l, int16_t g_96_l, char g_97_l, int32_t g_108_l, int32_t g_121_l, int32_t g_130_l, int32_t g_143_l, int16_t g_159_l, int16_t g_247_l, int32_t g_249_l, int32_t g_284_l, int32_t g_342_l, char g_354_l, int16_t g_368_l, int16_t g_398_l, int16_t g_410_l, int16_t g_411_l, char g_431_l, int32_t g_466_l, int32_t g_485_l, int32_t g_519_l, int16_t g_521_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x5fe0
int32_t g2 = 0xf7ffff; // 0x6020
char g3 = -9; // 0x6022
int32_t g4 = -9; // 0x6024
int32_t g5 = 0x79bdd86b; // 0x6028
int32_t g6 = 0x46e0aee; // 0x602c
int32_t g7 = 197; // 0x6030
int32_t g8 = 1; // 0x6034
int32_t g9 = -0x9ffde; // 0x6038
int32_t g10 = 0x3c4ffff6; // 0x603a
int32_t g11 = 0x78823c4f; // 0x603c
int32_t g12 = 0x8a7882; // 0x603e
int32_t g13 = 138; // 0x6040
int32_t g14 = -0x59d0406f; // 0x6044
int32_t g15 = 4; // 0x6048
int32_t g16 = 3; // 0x604c
int32_t g17 = -3; // 0x6050
int32_t g18 = 0x4420; // 0x6054
int32_t g19 = 0x7b06565b; // 0x6058
int32_t g20 = 0x3dbd97f; // 0x605c
int32_t g21 = -0x2ff4d; // 0x6060
int32_t g22 = 0x59c7fffd; // 0x6062
int32_t g23 = -0xa639; // 0x6064
int16_t g24 = -1; // 0x6066
int32_t g25 = 0x1ccb9f; // 0x6068
int32_t g26 = 0x1001c; // 0x606a
int32_t g27 = 1; // 0x606c
int32_t g28 = 1; // 0x6070
int32_t g29 = 0x1422b870; // 0x6074
int32_t g30 = 0xfadb; // 0x6078
int32_t g31 = -1; // 0x607c
int64_t g32 = 0; // 0x6080
int32_t g33 = 0; // 0x6090
int32_t g34 = 0; // 0x6094
int32_t * g35 = NULL; // 0x60a0
int32_t g36;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x5fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g36;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g32;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g32 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x6018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g32 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s520r2.c
// Address range: 0x1150 - 0x1498
// Line range:    385 - 426
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(int16_t *)&g2, "g_10", v1);
    transparent_crc((int32_t)g3, "g_11", v1);
    transparent_crc(g4, "g_30", v1);
    transparent_crc(253, "g_37", v1);
    transparent_crc(g5, "g_38", v1);
    transparent_crc(g6, "g_53", v1);
    transparent_crc((int32_t)*(char *)&g7, "g_56", v1);
    transparent_crc(g8, "g_74", v1);
    transparent_crc((int32_t)*(char *)&g9, "g_80", v1);
    transparent_crc((int32_t)*(int16_t *)&g10, "g_81", v1);
    transparent_crc((int32_t)*(int16_t *)&g11, "g_89", v1);
    transparent_crc((int32_t)*(int16_t *)&g12, "g_96", v1);
    transparent_crc((int32_t)*(char *)&g13, "g_97", v1);
    transparent_crc(g14, "g_108", v1);
    transparent_crc(g15, "g_121", v1);
    transparent_crc(g16, "g_130", v1);
    transparent_crc(g17, "g_143", v1);
    transparent_crc(0x46c1, "g_158", v1);
    transparent_crc((int32_t)*(int16_t *)&g18, "g_159", v1);
    transparent_crc((int32_t)*(int16_t *)&g33, "g_247", v1);
    transparent_crc(g19, "g_249", v1);
    transparent_crc(g34, "g_284", v1);
    transparent_crc(g20, "g_342", v1);
    transparent_crc((int32_t)*(char *)&g21, "g_354", v1);
    transparent_crc((int32_t)*(int16_t *)&g22, "g_368", v1);
    transparent_crc((int32_t)*(int16_t *)&g23, "g_398", v1);
    transparent_crc((int32_t)g24, "g_410", v1);
    transparent_crc((int32_t)*(int16_t *)&g25, "g_411", v1);
    transparent_crc((int32_t)*(char *)&g26, "g_431", v1);
    transparent_crc(g27, "g_466", v1);
    transparent_crc(g28, "g_485", v1);
    transparent_crc(g29, "g_519", v1);
    transparent_crc((int32_t)*(int16_t *)&g30, "g_521", v1);
    platform_main_end(-1 - *(int32_t *)0x607c, v1);
    return (int32_t)&g36 ^ (int32_t)&g36;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x14a0 - 0x14a6
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x14a0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x14b0 - 0x1545
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x1519
        int32_t v2 = i; // 0x14b0
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x14e6
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x1524
        *(int32_t *)(4 * i + (int64_t)&g35) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s520r2.c
// Address range: 0x1550 - 0x31d8
// Line range:    70 - 378
int32_t func_1(void) {
    // 0x1550
    set_var(-19, -9, -9, 0x79bdd86b, 0x46e0aee, 2, 1, 0, -10, 0x3c4f, 0x3f40, -118, -0x59d0406f, 0, 3, -3, 0x4420, 0, 0x7b06565b, -2, 0, -77, -3, 0x59c7, -1, -0x3461, 28, 1, 2, 1, -1317);
    return -36;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x31e0 - 0x3225
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x31e0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x3204
        printf("...checksum after hashing %s : %X\n", vname, -1 - g31);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x3230 - 0x3255
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x3230
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s520r2.c
// Address range: 0x3260 - 0x345d
// Line range:    60 - 62
int32_t set_var(int16_t g_10_l, char g_11_l, int32_t g_30_l, int32_t g_38_l, int32_t g_53_l, char g_56_l, int32_t g_74_l, char g_80_l, int16_t g_81_l, int16_t g_89_l, int16_t g_96_l, char g_97_l, int32_t g_108_l, int32_t g_121_l, int32_t g_130_l, int32_t g_143_l, int16_t g_159_l, int16_t g_247_l, int32_t g_249_l, int32_t g_284_l, int32_t g_342_l, char g_354_l, int16_t g_368_l, int16_t g_398_l, int16_t g_410_l, int16_t g_411_l, char g_431_l, int32_t g_466_l, int32_t g_485_l, int32_t g_519_l, int16_t g_521_l) {
    // 0x3260
    *(int16_t *)&g2 = g_10_l;
    g3 = g_11_l;
    g4 = g_30_l;
    g5 = g_38_l;
    g6 = g_53_l;
    *(char *)&g7 = g_56_l;
    g8 = g_74_l;
    *(char *)&g9 = g_80_l;
    *(int16_t *)&g10 = g_81_l;
    *(int16_t *)&g11 = g_89_l;
    *(int16_t *)&g12 = g_96_l;
    *(char *)&g13 = g_97_l;
    g14 = g_108_l;
    g15 = g_121_l;
    g16 = g_130_l;
    g17 = g_143_l;
    *(int16_t *)&g18 = g_159_l;
    *(int16_t *)&g33 = g_247_l;
    g19 = g_249_l;
    g34 = g_284_l;
    g20 = g_342_l;
    *(char *)&g21 = g_354_l;
    *(int16_t *)&g22 = g_368_l;
    *(int16_t *)&g23 = g_398_l;
    g24 = g_410_l;
    *(int16_t *)&g25 = g_411_l;
    *(char *)&g26 = g_431_l;
    g27 = g_466_l;
    g28 = g_485_l;
    g29 = g_519_l;
    *(int16_t *)&g30 = g_521_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3460 - 0x34bd
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x3460
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x34c0 - 0x3500
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g31;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g35); // 0x34f5
    g31 = v1 / 256 ^ v2;
}

// Address range: 0x3500 - 0x350d
int64_t _fini(void) {
    // 0x3500
    int64_t result; // 0x3500
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

