//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_3_l, int16_t g_13_l, int32_t g_14_l, int32_t g_30_l, int32_t g_49_l, int16_t g_50_l, int32_t g_53_l, int32_t g_94_l, int16_t g_95_l, int16_t g_96_l, char g_97_l, char g_121_l, char g_136_l, int32_t g_160_l, int16_t g_164_l, int16_t g_167_l, int16_t g_168_l, char g_177_l, int32_t g_183_l, char g_186_l, char g_192_l, char g_217_l, int16_t g_220_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x3fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x3f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x3f97;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x3eff); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s528retdec.c
// Address range: 0x11a0 - 0x156c
// Line range:    232 - 263
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x1e96)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    unsigned char v3 = *(char *)(v2 + 0x3e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x1e5c), v1);
    int16_t v4 = *(int16_t *)(v2 + 0x3e6a); // 0x123d
    transparent_crc((int32_t)v4, (char *)(v2 + 0x1e60), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x3e6c); // 0x1263
    transparent_crc(v5, (char *)(v2 + 0x1e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x3e70); // 0x1285
    transparent_crc(v6, (char *)(v2 + 0x1e6a), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x3e74); // 0x12a7
    transparent_crc(v7, (char *)(v2 + 0x1e6f), v1);
    uint16_t v8 = *(int16_t *)(v2 + 0x3ea4); // 0x12c9
    transparent_crc((int32_t)v8, (char *)(v2 + 0x1e74), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x3e78); // 0x12ec
    transparent_crc(v9, (char *)(v2 + 0x1e79), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x3ea8); // 0x130e
    transparent_crc(v10, (char *)(v2 + 0x1e7e), v1);
    int16_t v11 = *(int16_t *)(v2 + 0x3e7c); // 0x1330
    transparent_crc((int32_t)v11, (char *)(v2 + 0x1e83), v1);
    int16_t v12 = *(int16_t *)(v2 + 0x3e7e); // 0x1356
    transparent_crc((int32_t)v12, (char *)(v2 + 0x1e88), v1);
    unsigned char v13 = *(char *)(v2 + 0x3e80); // 0x137c
    transparent_crc((int32_t)v13, (char *)(v2 + 0x1e8d), v1);
    char v14 = *(char *)(v2 + 0x3e81); // 0x13a1
    transparent_crc((int32_t)v14, (char *)(v2 + 0x1e92), v1);
    char v15 = *(char *)(v2 + 0x3e82); // 0x13c4
    transparent_crc((int32_t)v15, (char *)(v2 + 0x1e98), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x3e84); // 0x13e7
    transparent_crc(v16, (char *)(v2 + 0x1e9e), v1);
    uint16_t v17 = *(int16_t *)(v2 + 0x3e88); // 0x1409
    transparent_crc((int32_t)v17, (char *)(v2 + 0x1ea4), v1);
    int16_t v18 = *(int16_t *)(v2 + 0x3e8a); // 0x142f
    transparent_crc((int32_t)v18, (char *)(v2 + 0x1eaa), v1);
    uint16_t v19 = *(int16_t *)(v2 + 0x3e8c); // 0x1455
    transparent_crc((int32_t)v19, (char *)(v2 + 0x1eb0), v1);
    char v20 = *(char *)(v2 + 0x3e8e); // 0x147b
    transparent_crc((int32_t)v20, (char *)(v2 + 0x1eb6), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x3e90); // 0x149e
    transparent_crc(v21, (char *)(v2 + 0x1ebc), v1);
    unsigned char v22 = *(char *)(v2 + 0x3e94); // 0x14c0
    transparent_crc((int32_t)v22, (char *)(v2 + 0x1ec2), v1);
    unsigned char v23 = *(char *)(v2 + 0x3e95); // 0x14e3
    transparent_crc((int32_t)v23, (char *)(v2 + 0x1ec8), v1);
    unsigned char v24 = *(char *)(v2 + 0x3e96); // 0x1506
    transparent_crc((int32_t)v24, (char *)(v2 + 0x1ece), v1);
    uint16_t v25 = *(int16_t *)(v2 + 0x3e98); // 0x1529
    transparent_crc((int32_t)v25, (char *)(v2 + 0x1ed4), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x3e9c), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1570 - 0x1575
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1570
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1580 - 0x1628
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x15fa
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x15c1
        while (v1 != 0) {
            // 0x15c7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1605
        int32_t v5; // 0x1580
        *(int32_t *)(v5 + 0x3acd + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s528retdec.c
// Address range: 0x1630 - 0x2273
// Line range:    60 - 225
char func_1(void) {
    // 0x1630
    set_var(-12, -0x14b4, -8, -0x107e963f, 1, 0, 5, 0, 0x41ab, 1181, 47, -18, -92, 3, 0x79af, 0x3468, 4, -6, -0x363fde17, 53, 123, 7, -7);
    return -18;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2280 - 0x22df
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2280
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2280
    if (v1 != 0) {
        // 0x22b4
        printf((char *)(v1 + 3578));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x22e0 - 0x2314
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x22e0
    int32_t v1; // 0x22e0
    printf((char *)(v1 + 3517));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s528retdec.c
// Address range: 0x2320 - 0x245f
// Line range:    50 - 52
int32_t set_var(char g_3_l, int16_t g_13_l, int32_t g_14_l, int32_t g_30_l, int32_t g_49_l, int16_t g_50_l, int32_t g_53_l, int32_t g_94_l, int16_t g_95_l, int16_t g_96_l, char g_97_l, char g_121_l, char g_136_l, int32_t g_160_l, int16_t g_164_l, int16_t g_167_l, int16_t g_168_l, char g_177_l, int32_t g_183_l, char g_186_l, char g_192_l, char g_217_l, int16_t g_220_l) {
    // 0x2320
    int32_t v1; // 0x2320
    *(char *)(v1 + 0x2cec) = (char)g_13_l;
    *(int16_t *)(v1 + 0x2cee) = (int16_t)g_14_l;
    *(int32_t *)(v1 + 0x2cf0) = g_30_l;
    *(int32_t *)(v1 + 0x2cf4) = g_49_l;
    *(int32_t *)(v1 + 0x2cf8) = (int32_t)g_50_l;
    *(int16_t *)(v1 + 0x2d28) = (int16_t)g_53_l;
    *(int32_t *)(v1 + 0x2cfc) = g_94_l;
    *(int32_t *)(v1 + 0x2d2c) = (int32_t)g_95_l;
    *(int16_t *)(v1 + 0x2d00) = g_96_l;
    *(int16_t *)(v1 + 0x2d02) = (int16_t)g_97_l;
    *(char *)(v1 + 0x2d04) = g_121_l;
    *(char *)(v1 + 0x2d05) = g_136_l;
    *(char *)(v1 + 0x2d06) = (char)g_160_l;
    *(int32_t *)(v1 + 0x2d08) = (int32_t)g_164_l;
    *(int16_t *)(v1 + 0x2d0c) = g_167_l;
    *(int16_t *)(v1 + 0x2d0e) = g_168_l;
    *(int16_t *)(v1 + 0x2d10) = (int16_t)g_177_l;
    *(char *)(v1 + 0x2d12) = (char)g_183_l;
    *(int32_t *)(v1 + 0x2d14) = (int32_t)g_186_l;
    *(char *)(v1 + 0x2d18) = g_192_l;
    *(char *)(v1 + 0x2d19) = g_217_l;
    *(char *)(v1 + 0x2d1a) = (char)g_220_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2460 - 0x24e0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x2460
    int32_t v1; // 0x2460
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x24e0 - 0x2524
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x24e0
    int32_t v1; // 0x24e0
    int32_t * v2 = (int32_t *)(v1 + 0x2b5f); // 0x24f3
    uint32_t v3 = *v2; // 0x24f3
    char v4; // 0x24e0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2b6f + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x2524 - 0x253c
int32_t _fini(void) {
    // 0x2524
    int32_t v1; // 0x2524
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

