//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_9_l, char g_23_l, int32_t g_38_l, char g_84_l, int32_t g_85_l, int16_t g_86_l, int32_t g_129_l, int32_t g_148_l, int16_t g_149_l, int32_t g_150_l, int32_t g_178_l, int16_t g_192_l, char g_239_l, int32_t g_248_l, char g_258_l, int32_t g_281_l, int32_t g_298_l, int16_t g_309_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4fe0
int32_t g2 = -2; // 0x5020
int32_t g3 = 198; // 0x5024
int32_t g4 = 1; // 0x5028
int32_t g5 = 225; // 0x502c
int32_t g6 = -0x182391d1; // 0x5030
int16_t g7 = -0x2db9; // 0x5034
int32_t g8 = -0x3b13f9a5; // 0x5038
int32_t g9 = -4; // 0x503c
int32_t g10 = 4; // 0x5040
int32_t g11 = 0x50425ff9; // 0x5044
int32_t g12 = -0x1b2510ee; // 0x5048
int32_t g13 = 0xfaaea4; // 0x504c
int32_t g14 = -0xff06; // 0x504e
int32_t g15 = -1; // 0x5050
int32_t g16 = 164; // 0x5054
int32_t g17 = -1; // 0x5058
int32_t g18 = -1; // 0x505c
int32_t g19 = 0x4095; // 0x5060
int32_t g20 = -1; // 0x5064
char g21 = 0; // 0x5070
int32_t * g22 = NULL; // 0x5080
int32_t g23;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g23;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return 0x5068;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (g21 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x5018);
    }
    int64_t result2 = function_1080(); // 0x1118
    g21 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s561retdec.c
// Address range: 0x1150 - 0x1354
// Line range:    270 - 296
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(g2, "g_9", v1);
    transparent_crc((int32_t)*(char *)&g3, "g_23", v1);
    transparent_crc(g4, "g_38", v1);
    transparent_crc((int32_t)*(char *)&g5, "g_84", v1);
    transparent_crc(g6, "g_85", v1);
    transparent_crc((int32_t)g7, "g_86", v1);
    transparent_crc(g8, "g_129", v1);
    transparent_crc(g9, "g_148", v1);
    transparent_crc((int32_t)*(int16_t *)&g10, "g_149", v1);
    transparent_crc(g11, "g_150", v1);
    transparent_crc(g12, "g_178", v1);
    transparent_crc((int32_t)*(int16_t *)&g13, "g_192", v1);
    transparent_crc((int32_t)*(char *)&g14, "g_239", v1);
    transparent_crc(g15, "g_248", v1);
    transparent_crc((int32_t)*(char *)&g16, "g_258", v1);
    transparent_crc(g17, "g_281", v1);
    transparent_crc(g18, "g_298", v1);
    transparent_crc((int32_t)*(int16_t *)&g19, "g_309", v1);
    platform_main_end(-1 - *(int32_t *)0x5064, v1);
    return (int32_t)&g23 ^ (int32_t)&g23;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1360 - 0x1366
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1360
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1370 - 0x1405
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x13d9
        int32_t v2 = i; // 0x1370
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x13a6
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x13e4
        *(int32_t *)(4 * i + (int64_t)&g22) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s561retdec.c
// Address range: 0x1410 - 0x2967
// Line range:    55 - 263
int32_t func_1(void) {
    // 0x2884
    set_var(-2, -58, 1, -31, -0x182391d1, -0x2db9, -0x3b13f9a5, -4, 4, 0x50425ff9, -0x1b2510ee, -0x515c, -6, -1, -92, -1, -1, 0x4095);
    return 2;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2970 - 0x29b5
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2970
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x2994
        printf("...checksum after hashing %s : %X\n", vname, -1 - g20);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x29c0 - 0x29e5
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x29c0
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s561retdec.c
// Address range: 0x29f0 - 0x2aee
// Line range:    45 - 47
int32_t set_var(int32_t g_9_l, char g_23_l, int32_t g_38_l, char g_84_l, int32_t g_85_l, int16_t g_86_l, int32_t g_129_l, int32_t g_148_l, int16_t g_149_l, int32_t g_150_l, int32_t g_178_l, int16_t g_192_l, char g_239_l, int32_t g_248_l, char g_258_l, int32_t g_281_l, int32_t g_298_l, int16_t g_309_l) {
    // 0x29f0
    g2 = g_9_l;
    *(char *)&g3 = g_23_l;
    g4 = g_38_l;
    *(char *)&g5 = g_84_l;
    g6 = g_85_l;
    g7 = g_86_l;
    g8 = g_129_l;
    g9 = g_148_l;
    *(int16_t *)&g10 = g_149_l;
    g11 = g_150_l;
    g12 = g_178_l;
    *(int16_t *)&g13 = g_192_l;
    *(char *)&g14 = g_239_l;
    g15 = g_248_l;
    *(char *)&g16 = g_258_l;
    g17 = g_281_l;
    g18 = g_298_l;
    *(int16_t *)&g19 = g_309_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2af0 - 0x2b4d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x2af0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2b50 - 0x2b90
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g20;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g22); // 0x2b85
    g20 = v1 / 256 ^ v2;
}

// Address range: 0x2b90 - 0x2b9d
int64_t _fini(void) {
    // 0x2b90
    int64_t result; // 0x2b90
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

