//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_4_l, int32_t g_15_l, int16_t g_16_l, int32_t g_25_l, int32_t g_51_l, int32_t g_86_l, int32_t g_87_l, int32_t g_89_l, char g_90_l, int32_t g_175_l, char g_176_l, int32_t g_183_l, int16_t g_194_l, char g_195_l, char g_216_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x3fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x3f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x3f93;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x3efb); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s625retdec.c
// Address range: 0x11a0 - 0x1442
// Line range:    209 - 232
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x1e72)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x3e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x1e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x3e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x1e60), v1);
    int16_t v5 = *(int16_t *)(v2 + 0x3e70); // 0x125e
    transparent_crc((int32_t)v5, (char *)(v2 + 0x1e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x3e74); // 0x1281
    transparent_crc(v6, (char *)(v2 + 0x1e6a), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x3e78); // 0x12a3
    transparent_crc(v7, (char *)(v2 + 0x1e6f), v1);
    int32_t v8 = *(int32_t *)(v2 + 0x3ea0); // 0x12c5
    transparent_crc(v8, (char *)(v2 + 0x1e74), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x3e7c); // 0x12e7
    transparent_crc(v9, (char *)(v2 + 0x1e79), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x3e80); // 0x1309
    transparent_crc(v10, (char *)(v2 + 0x1e7e), v1);
    char v11 = *(char *)(v2 + 0x3e84); // 0x132b
    transparent_crc((int32_t)v11, (char *)(v2 + 0x1e83), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x3e88); // 0x134e
    transparent_crc(v12, (char *)(v2 + 0x1e88), v1);
    char v13 = *(char *)(v2 + 0x3e8c); // 0x1370
    transparent_crc((int32_t)v13, (char *)(v2 + 0x1e8e), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x3e90); // 0x1393
    transparent_crc(v14, (char *)(v2 + 0x1e94), v1);
    int16_t v15 = *(int16_t *)(v2 + 0x3e94); // 0x13b5
    transparent_crc((int32_t)v15, (char *)(v2 + 0x1e9a), v1);
    unsigned char v16 = *(char *)(v2 + 0x3e96); // 0x13d8
    transparent_crc((int32_t)v16, (char *)(v2 + 0x1ea0), v1);
    unsigned char v17 = *(char *)(v2 + 0x3e97); // 0x13fd
    transparent_crc((int32_t)v17, (char *)(v2 + 0x1ea6), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x3e98), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1450 - 0x1455
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1450
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1460 - 0x1508
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x14da
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x14a1
        while (v1 != 0) {
            // 0x14a7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x14e5
        int32_t v5; // 0x1460
        *(int32_t *)(v5 + 0x3be5 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s625retdec.c
// Address range: 0x1510 - 0x2249
// Line range:    52 - 202
char func_1(void) {
    // 0x214f
    set_var(123, 3, 0, 5, -0x75089601, 0, 0x61ffe8b4, -1, 1, 5, 75, -0x1cfb013b, 4093, 3, 1);
    return 123;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2250 - 0x22af
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2250
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2250
    if (v1 != 0) {
        // 0x2284
        printf((char *)(v1 + 3580));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x22b0 - 0x22e4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x22b0
    int32_t v1; // 0x22b0
    printf((char *)(v1 + 3519));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s625retdec.c
// Address range: 0x22f0 - 0x23bd
// Line range:    42 - 44
int32_t set_var(int32_t g_4_l, int32_t g_15_l, int16_t g_16_l, int32_t g_25_l, int32_t g_51_l, int32_t g_86_l, int32_t g_87_l, int32_t g_89_l, char g_90_l, int32_t g_175_l, char g_176_l, int32_t g_183_l, int16_t g_194_l, char g_195_l, char g_216_l) {
    // 0x22f0
    int32_t v1; // 0x22f0
    *(int32_t *)(v1 + 0x2d1c) = g_15_l;
    *(int32_t *)(v1 + 0x2d20) = (int32_t)g_16_l;
    *(int16_t *)(v1 + 0x2d24) = (int16_t)g_25_l;
    *(int32_t *)(v1 + 0x2d28) = g_51_l;
    *(int32_t *)(v1 + 0x2d2c) = g_86_l;
    *(int32_t *)(v1 + 0x2d54) = g_87_l;
    *(int32_t *)(v1 + 0x2d30) = g_89_l;
    *(int32_t *)(v1 + 0x2d34) = (int32_t)g_90_l;
    *(char *)(v1 + 0x2d38) = (char)g_175_l;
    *(int32_t *)(v1 + 0x2d3c) = (int32_t)g_176_l;
    *(char *)(v1 + 0x2d40) = (char)g_183_l;
    *(int32_t *)(v1 + 0x2d44) = (int32_t)g_194_l;
    *(int16_t *)(v1 + 0x2d48) = (int16_t)g_195_l;
    *(char *)(v1 + 0x2d4a) = g_216_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x23c0 - 0x2440
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x23c0
    int32_t v1; // 0x23c0
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2440 - 0x2484
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x2440
    int32_t v1; // 0x2440
    int32_t * v2 = (int32_t *)(v1 + 0x2bfb); // 0x2453
    uint32_t v3 = *v2; // 0x2453
    char v4; // 0x2440
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2c07 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x2484 - 0x249c
int32_t _fini(void) {
    // 0x2484
    int32_t v1; // 0x2484
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

