//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int16_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_12_l, char g_33_l, int32_t g_35_l, char g_39_l, int16_t g_42_l, int16_t g_51_l, int16_t g_92_l, int32_t g_95_l, char g_97_l, char g_102_l, int32_t g_117_l, char g_118_l, int32_t g_119_l, int32_t g_144_l, int32_t g_145_l, char g_262_l, int32_t g_270_l, int16_t g_272_l, int16_t g_273_l, int16_t g_319_l, int16_t g_320_l, int32_t g_325_l, int32_t g_419_l, int32_t g_420_l, int32_t g_516_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int16_t g1 = -0x7500; // 0x1241
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x5fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x5f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g2);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x10b0
    return v1 + 0x5fab;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x5f13); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s629r2.c
// Address range: 0x11a0 - 0x15db
// Line range:    415 - 450
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x3e7c)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x5e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x3e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x5e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x3e60), v1);
    unsigned char v5 = *(char *)(v2 + 0x5e70); // 0x125e
    transparent_crc((int32_t)v5, (char *)(v2 + 0x3e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x5eb8); // 0x1281
    transparent_crc(v6, (char *)(v2 + 0x3e6a), v1);
    unsigned char v7 = *(char *)(v2 + 0x5e71); // 0x12a3
    transparent_crc((int32_t)v7, (char *)(v2 + 0x3e6f), v1);
    uint16_t v8 = *(int16_t *)(v2 + 0x5e72); // 0x12c6
    transparent_crc((int32_t)v8, (char *)(v2 + 0x3e74), v1);
    int16_t v9 = *(int16_t *)(v2 + 0x5e74); // 0x12e9
    transparent_crc((int32_t)v9, (char *)(v2 + 0x3e79), v1);
    int16_t v10 = *(int16_t *)(v2 + 0x5e76); // 0x130c
    transparent_crc((int32_t)v10, (char *)(v2 + 0x3e7e), v1);
    int32_t v11 = *(int32_t *)(v2 + 0x5e78); // 0x132f
    transparent_crc(v11, (char *)(v2 + 0x3e83), v1);
    char v12 = *(char *)(v2 + 0x5e7c); // 0x1351
    transparent_crc((int32_t)v12, (char *)(v2 + 0x3e88), v1);
    unsigned char v13 = *(char *)(v2 + 0x5e7d); // 0x1374
    transparent_crc((int32_t)v13, (char *)(v2 + 0x3e8d), v1);
    transparent_crc(0x37b8604, (char *)(v2 + 0x3e93), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x5e80); // 0x13b7
    transparent_crc(v14, (char *)(v2 + 0x3e99), v1);
    char v15 = *(char *)(v2 + 0x5e84); // 0x13d9
    transparent_crc((int32_t)v15, (char *)(v2 + 0x3e9f), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x5e88); // 0x13fc
    transparent_crc(v16, (char *)(v2 + 0x3ea5), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x5e8c); // 0x141e
    transparent_crc(v17, (char *)(v2 + 0x3eab), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x5e90); // 0x1440
    transparent_crc(v18, (char *)(v2 + 0x3eb1), v1);
    unsigned char v19 = *(char *)(v2 + 0x5e94); // 0x1462
    transparent_crc((int32_t)v19, (char *)(v2 + 0x3eb7), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x5e98); // 0x1485
    transparent_crc(v20, (char *)(v2 + 0x3ebd), v1);
    int16_t v21 = *(int16_t *)(v2 + 0x5e9c); // 0x14a7
    transparent_crc((int32_t)v21, (char *)(v2 + 0x3ec3), v1);
    int16_t v22 = *(int16_t *)(v2 + 0x5e9e); // 0x14ca
    transparent_crc((int32_t)v22, (char *)(v2 + 0x3ec9), v1);
    int16_t v23 = *(int16_t *)(v2 + 0x5ea0); // 0x14ed
    transparent_crc((int32_t)v23, (char *)(v2 + 0x3ecf), v1);
    uint16_t v24 = *(int16_t *)(v2 + 0x5ea2); // 0x1510
    transparent_crc((int32_t)v24, (char *)(v2 + 0x3ed5), v1);
    int32_t v25 = *(int32_t *)(v2 + 0x5ea4); // 0x1533
    transparent_crc(v25, (char *)(v2 + 0x3edb), v1);
    int32_t v26 = *(int32_t *)(v2 + 0x5ebc); // 0x1555
    transparent_crc(v26, (char *)(v2 + 0x3ee1), v1);
    int32_t v27 = *(int32_t *)(v2 + 0x5ea8); // 0x1577
    transparent_crc(v27, (char *)(v2 + 0x3ee7), v1);
    int32_t v28 = *(int32_t *)(v2 + 0x5eac); // 0x1599
    transparent_crc(v28, (char *)(v2 + 0x3eed), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x5eb0), v1);
    return 0;
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x15e0 - 0x15e5
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x15e0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x15f0 - 0x1698
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x166a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1631
        while (v1 != 0) {
            // 0x1637
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1675
        int32_t v5; // 0x15f0
        *(int32_t *)(v5 + 0x5a71 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s629r2.c
// Address range: 0x16a0 - 0x4447
// Line range:    64 - 408
int16_t func_1(void) {
    // 0x16a0
    set_var(24, -1, -9, 0, 33, -5, 24, (int16_t)&g1, 0, -4, 1, -0x6ec0f7d1, -85, -0x1173ff82, 0x5ad653c0, -0x15990cee, -27, 4, -0x19e5, 6, -0x21b8, -0x3d62, -0x7bc779a9, 0, 34, 0xc45464b);
    return 0x79e6;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4450 - 0x44af
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x4450
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x4450
    if (v1 != 0) {
        // 0x4484
        printf((char *)(v1 + 3139));
    }
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x44b0 - 0x44e4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x44b0
    int32_t v1; // 0x44b0
    printf((char *)(v1 + 3078));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s629r2.c
// Address range: 0x44f0 - 0x4650
// Line range:    54 - 56
int32_t set_var(int32_t g_2_l, int32_t g_12_l, char g_33_l, int32_t g_35_l, char g_39_l, int16_t g_42_l, int16_t g_51_l, int16_t g_92_l, int32_t g_95_l, char g_97_l, char g_102_l, int32_t g_117_l, char g_118_l, int32_t g_119_l, int32_t g_144_l, int32_t g_145_l, char g_262_l, int32_t g_270_l, int16_t g_272_l, int16_t g_273_l, int16_t g_319_l, int16_t g_320_l, int32_t g_325_l, int32_t g_419_l, int32_t g_420_l, int32_t g_516_l) {
    // 0x44f0
    int32_t v1; // 0x44f0
    *(int32_t *)(v1 + 0x2b1c) = g_12_l;
    *(int32_t *)(v1 + 0x2b20) = (int32_t)g_33_l;
    *(char *)(v1 + 0x2b24) = (char)g_35_l;
    *(int32_t *)(v1 + 0x2b6c) = (int32_t)g_39_l;
    *(char *)(v1 + 0x2b25) = (char)g_42_l;
    *(int16_t *)(v1 + 0x2b26) = g_51_l;
    *(int16_t *)(v1 + 0x2b28) = g_92_l;
    *(int16_t *)(v1 + 0x2b2a) = (int16_t)g_95_l;
    *(int32_t *)(v1 + 0x2b2c) = (int32_t)g_97_l;
    *(char *)(v1 + 0x2b30) = g_102_l;
    *(char *)(v1 + 0x2b31) = (char)g_117_l;
    *(int32_t *)(v1 + 0x2b34) = (int32_t)g_118_l;
    *(char *)(v1 + 0x2b38) = (char)g_119_l;
    *(int32_t *)(v1 + 0x2b3c) = g_144_l;
    *(int32_t *)(v1 + 0x2b40) = g_145_l;
    *(int32_t *)(v1 + 0x2b44) = (int32_t)g_262_l;
    *(char *)(v1 + 0x2b48) = (char)g_270_l;
    *(int32_t *)(v1 + 0x2b4c) = (int32_t)g_272_l;
    *(int16_t *)(v1 + 0x2b50) = g_273_l;
    *(int16_t *)(v1 + 0x2b52) = g_319_l;
    *(int16_t *)(v1 + 0x2b54) = g_320_l;
    *(int16_t *)(v1 + 0x2b56) = (int16_t)g_325_l;
    *(int32_t *)(v1 + 0x2b58) = g_419_l;
    *(int32_t *)(v1 + 0x2b70) = g_420_l;
    *(int32_t *)(v1 + 0x2b5c) = g_516_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4650 - 0x46d0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x4650
    int32_t v1; // 0x4650
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x46d0 - 0x4714
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x46d0
    int32_t v1; // 0x46d0
    int32_t * v2 = (int32_t *)(v1 + 0x2983); // 0x46e3
    uint32_t v3 = *v2; // 0x46e3
    char v4; // 0x46d0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2993 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x4714 - 0x472c
int32_t _fini(void) {
    // 0x4714
    int32_t v1; // 0x4714
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

