//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_2_l, char g_4_l, char g_8_l, int16_t g_9_l, int16_t g_16_l, char g_20_l, int32_t g_38_l, char g_39_l, int16_t g_43_l, int16_t g_47_l, char g_48_l, char g_50_l, char g_53_l, int16_t g_88_l, int32_t g_110_l, int16_t g_134_l, int16_t g_156_l, int32_t g_162_l, int32_t g_169_l, int32_t g_259_l, int32_t g_286_l, int32_t g_337_l, int16_t g_365_l, int16_t g_382_l, int32_t g_399_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x4f9b;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f03); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s631retdec.c
// Address range: 0x11a0 - 0x15a2
// Line range:    312 - 345
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2e5c)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    unsigned char v3 = *(char *)(v2 + 0x4e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x2e5e), v1);
    unsigned char v4 = *(char *)(v2 + 0x4e69); // 0x123d
    transparent_crc((int32_t)v4, (char *)(v2 + 0x2e62), v1);
    unsigned char v5 = *(char *)(v2 + 0x4e6a); // 0x1260
    transparent_crc((int32_t)v5, (char *)(v2 + 0x2e66), v1);
    uint16_t v6 = *(int16_t *)(v2 + 0x4e6c); // 0x1283
    transparent_crc((int32_t)v6, (char *)(v2 + 0x2e6a), v1);
    int16_t v7 = *(int16_t *)(v2 + 0x4e6e); // 0x12a6
    transparent_crc((int32_t)v7, (char *)(v2 + 0x2e6e), v1);
    char v8 = *(char *)(v2 + 0x4e70); // 0x12cc
    transparent_crc((int32_t)v8, (char *)(v2 + 0x2e73), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x4e74); // 0x12ef
    transparent_crc(v9, (char *)(v2 + 0x2e78), v1);
    unsigned char v10 = *(char *)(v2 + 0x4e78); // 0x1311
    transparent_crc((int32_t)v10, (char *)(v2 + 0x2e7d), v1);
    uint16_t v11 = *(int16_t *)(v2 + 0x4e7a); // 0x1334
    transparent_crc((int32_t)v11, (char *)(v2 + 0x2e82), v1);
    int16_t v12 = *(int16_t *)(v2 + 0x4e7c); // 0x1357
    transparent_crc((int32_t)v12, (char *)(v2 + 0x2e87), v1);
    char v13 = *(char *)(v2 + 0x4e7e); // 0x137a
    transparent_crc((int32_t)v13, (char *)(v2 + 0x2e8c), v1);
    char v14 = *(char *)(v2 + 0x4e7f); // 0x139f
    transparent_crc((int32_t)v14, (char *)(v2 + 0x2e91), v1);
    unsigned char v15 = *(char *)(v2 + 0x4ea8); // 0x13c2
    transparent_crc((int32_t)v15, (char *)(v2 + 0x2e96), v1);
    uint16_t v16 = *(int16_t *)(v2 + 0x4e80); // 0x13e5
    transparent_crc((int32_t)v16, (char *)(v2 + 0x2e9b), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x4eac); // 0x1408
    transparent_crc(v17, (char *)(v2 + 0x2ea0), v1);
    int16_t v18 = *(int16_t *)(v2 + 0x4e82); // 0x142a
    transparent_crc((int32_t)v18, (char *)(v2 + 0x2ea6), v1);
    uint16_t v19 = *(int16_t *)(v2 + 0x4eb0); // 0x144d
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eac), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x4e84); // 0x1470
    transparent_crc(v20, (char *)(v2 + 0x2eb2), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x4e88); // 0x1492
    transparent_crc(v21, (char *)(v2 + 0x2eb8), v1);
    int32_t v22 = *(int32_t *)(v2 + 0x4e8c); // 0x14b4
    transparent_crc(v22, (char *)(v2 + 0x2ebe), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x4e90); // 0x14d6
    transparent_crc(v23, (char *)(v2 + 0x2ec4), v1);
    int32_t v24 = *(int32_t *)(v2 + 0x4e94); // 0x14f8
    transparent_crc(v24, (char *)(v2 + 0x2eca), v1);
    int16_t v25 = *(int16_t *)(v2 + 0x4e98); // 0x151a
    transparent_crc((int32_t)v25, (char *)(v2 + 0x2ed0), v1);
    uint16_t v26 = *(int16_t *)(v2 + 0x4e9a); // 0x153d
    transparent_crc((int32_t)v26, (char *)(v2 + 0x2ed6), v1);
    int32_t v27 = *(int32_t *)(v2 + 0x4e9c); // 0x1560
    transparent_crc(v27, (char *)(v2 + 0x2edc), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4ea0), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x15b0 - 0x15b5
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x15b0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x15c0 - 0x1668
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x163a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1601
        while (v1 != 0) {
            // 0x1607
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1645
        int32_t v5; // 0x15c0
        *(int32_t *)(v5 + 0x4a95 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s631retdec.c
// Address range: 0x1670 - 0x2f10
// Line range:    62 - 305
char func_1(void) {
    // 0x2d0e
    set_var(-12, 99, -8, 6, -0x1fd8, -28, -2, 55, 4, -0x14f9, -9, 1, 0, 0x73a6, 0, -1, 0, 1, -0x2e8c356c, -0x5bfd31e8, -0x207b4c8c, 3, 0x31c8, -9, -3);
    return -108;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2f10 - 0x2f6f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2f10
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2f10
    if (v1 != 0) {
        // 0x2f44
        printf((char *)(v1 + 0x1172));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x2f70 - 0x2fa4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2f70
    int32_t v1; // 0x2f70
    printf((char *)(v1 + 0x1135));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s631retdec.c
// Address range: 0x2fb0 - 0x310a
// Line range:    52 - 54
int32_t set_var(char g_2_l, char g_4_l, char g_8_l, int16_t g_9_l, int16_t g_16_l, char g_20_l, int32_t g_38_l, char g_39_l, int16_t g_43_l, int16_t g_47_l, char g_48_l, char g_50_l, char g_53_l, int16_t g_88_l, int32_t g_110_l, int16_t g_134_l, int16_t g_156_l, int32_t g_162_l, int32_t g_169_l, int32_t g_259_l, int32_t g_286_l, int32_t g_337_l, int16_t g_365_l, int16_t g_382_l, int32_t g_399_l) {
    // 0x2fb0
    int32_t v1; // 0x2fb0
    *(char *)(v1 + 0x305c) = g_4_l;
    *(char *)(v1 + 0x305d) = g_8_l;
    *(char *)(v1 + 0x305e) = (char)g_9_l;
    *(int16_t *)(v1 + 0x3060) = g_16_l;
    *(int16_t *)(v1 + 0x3062) = (int16_t)g_20_l;
    *(char *)(v1 + 0x3064) = (char)g_38_l;
    *(int32_t *)(v1 + 0x3068) = (int32_t)g_39_l;
    *(char *)(v1 + 0x306c) = (char)g_43_l;
    *(int16_t *)(v1 + 0x306e) = g_47_l;
    *(int16_t *)(v1 + 0x3070) = (int16_t)g_48_l;
    *(char *)(v1 + 0x3072) = g_50_l;
    *(char *)(v1 + 0x3073) = g_53_l;
    *(char *)(v1 + 0x309c) = (char)g_88_l;
    *(int16_t *)(v1 + 0x3074) = (int16_t)g_110_l;
    *(int32_t *)(v1 + 0x30a0) = (int32_t)g_134_l;
    *(int16_t *)(v1 + 0x3076) = g_156_l;
    *(int16_t *)(v1 + 0x30a4) = (int16_t)g_162_l;
    *(int32_t *)(v1 + 0x3078) = g_169_l;
    *(int32_t *)(v1 + 0x307c) = g_259_l;
    *(int32_t *)(v1 + 0x3080) = g_286_l;
    *(int32_t *)(v1 + 0x3084) = g_337_l;
    *(int32_t *)(v1 + 0x3088) = (int32_t)g_365_l;
    *(int16_t *)(v1 + 0x308c) = g_382_l;
    *(int16_t *)(v1 + 0x308e) = (int16_t)g_399_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3110 - 0x3190
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x3110
    int32_t v1; // 0x3110
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3190 - 0x31d4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x3190
    int32_t v1; // 0x3190
    int32_t * v2 = (int32_t *)(v1 + 0x2eb3); // 0x31a3
    uint32_t v3 = *v2; // 0x31a3
    char v4; // 0x3190
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2ec7 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x31d4 - 0x31ec
int32_t _fini(void) {
    // 0x31d4
    int32_t v1; // 0x31d4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

