//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_18_l, int32_t g_26_l, int32_t g_27_l, int16_t g_31_l, int16_t g_107_l, int32_t g_125_l, int32_t g_126_l, int32_t g_231_l, int32_t g_233_l, int16_t g_304_l, char g_312_l, int16_t g_313_l, char g_324_l, char g_325_l, int16_t g_358_l, int32_t g_369_l, char g_378_l, char g_379_l, char g_456_l, int32_t g_526_l, int16_t g_527_l, char g_534_l, char g_566_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x5fe0
int32_t g2 = 0x60477862; // 0x6020
int32_t g3 = -0x49901405; // 0x6024
int32_t g4 = 0x6b5cfda6; // 0x6028
int32_t g5 = 0xbe2f; // 0x602c
int32_t g6 = 0x665bec7; // 0x6030
int32_t g7 = 0xff22b77; // 0x6034
int32_t g8 = 1; // 0x6038
int32_t g9 = 0x8ffff; // 0x603c
char g10 = 8; // 0x603e
int32_t g11 = -0x664c98; // 0x6040
int32_t g12 = 0x2ff99; // 0x6042
int32_t g13 = 767; // 0x6043
int32_t g14 = 2; // 0x6044
int32_t g15 = -0x72b684c6; // 0x6048
int32_t g16 = 0x102b0; // 0x604c
int32_t g17 = 0x32000102; // 0x604d
char g18 = 1; // 0x604e
int32_t g19 = 0x59515032; // 0x6050
int32_t g20 = -0xcc0004; // 0x6054
int64_t g21; // 0x6056
int64_t g22; // 0x6057
int32_t g23 = -1; // 0x6058
int64_t g24 = 0; // 0x6060
int32_t g25 = 0; // 0x6070
int32_t g26 = 0; // 0x6074
int32_t g27 = 0; // 0x6078
int32_t * g28 = NULL; // 0x6080
int32_t g29;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x5fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g29;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g24;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g24 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x6018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g24 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s750r2.c
// Address range: 0x1150 - 0x13d9
// Line range:    382 - 414
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(g2, "g_2", v1);
    transparent_crc(g3, "g_18", v1);
    transparent_crc(g4, "g_26", v1);
    transparent_crc(g25, "g_27", v1);
    transparent_crc((int32_t)*(int16_t *)&g5, "g_31", v1);
    transparent_crc((int32_t)*(int16_t *)&g26, "g_107", v1);
    transparent_crc(g6, "g_125", v1);
    transparent_crc(g7, "g_126", v1);
    transparent_crc(g27, "g_231", v1);
    transparent_crc(g8, "g_233", v1);
    transparent_crc((int32_t)*(int16_t *)&g9, "g_304", v1);
    transparent_crc((int32_t)g10, "g_312", v1);
    transparent_crc((int32_t)*(int16_t *)&g11, "g_313", v1);
    transparent_crc((int32_t)*(char *)&g12, "g_324", v1);
    transparent_crc((int32_t)*(char *)&g13, "g_325", v1);
    transparent_crc((int32_t)*(int16_t *)&g14, "g_358", v1);
    transparent_crc(g15, "g_369", v1);
    transparent_crc((int32_t)*(char *)&g16, "g_378", v1);
    transparent_crc((int32_t)*(char *)&g17, "g_379", v1);
    transparent_crc((int32_t)g18, "g_456", v1);
    transparent_crc(g19, "g_526", v1);
    transparent_crc((int32_t)*(int16_t *)&g20, "g_527", v1);
    transparent_crc((int32_t)*(char *)0x6056, "g_534", v1);
    transparent_crc((int32_t)*(char *)0x6057, "g_566", v1);
    platform_main_end(-1 - *(int32_t *)0x6058, v1);
    return (int32_t)&g29 ^ (int32_t)&g29;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x13e0 - 0x13e6
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x13e0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x13f0 - 0x1485
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x1459
        int32_t v2 = i; // 0x13f0
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x1426
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x1464
        *(int32_t *)(4 * i + (int64_t)&g28) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s750r2.c
// Address range: 0x1490 - 0x37fe
// Line range:    61 - 375
char func_1(void) {
    // 0x201d
    set_var(0, -0x49901405, 0x6b5cfda6, -14, -0x41d1, 0, 0, 0xff22b77, 0, 1, -1, 8, -0x4c98, -103, -1, 2, -0x72b684c6, -80, 2, 1, 0x59515032, -4, 51, -1);
    return -93;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3800 - 0x3845
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x3800
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x3824
        printf("...checksum after hashing %s : %X\n", vname, -1 - g23);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x3850 - 0x3875
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x3850
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s750r2.c
// Address range: 0x3880 - 0x3a0b
// Line range:    51 - 53
int32_t set_var(int32_t g_2_l, int32_t g_18_l, int32_t g_26_l, int32_t g_27_l, int16_t g_31_l, int16_t g_107_l, int32_t g_125_l, int32_t g_126_l, int32_t g_231_l, int32_t g_233_l, int16_t g_304_l, char g_312_l, int16_t g_313_l, char g_324_l, char g_325_l, int16_t g_358_l, int32_t g_369_l, char g_378_l, char g_379_l, char g_456_l, int32_t g_526_l, int16_t g_527_l, char g_534_l, char g_566_l) {
    // 0x3880
    g2 = g_2_l;
    g3 = g_18_l;
    g4 = g_26_l;
    g25 = g_27_l;
    *(int16_t *)&g5 = g_31_l;
    *(int16_t *)&g26 = g_107_l;
    g6 = g_125_l;
    g7 = g_126_l;
    g27 = g_231_l;
    g8 = g_233_l;
    *(int16_t *)&g9 = g_304_l;
    g10 = g_312_l;
    *(int16_t *)&g11 = g_313_l;
    *(char *)&g12 = g_324_l;
    *(char *)&g13 = g_325_l;
    *(int16_t *)&g14 = g_358_l;
    g15 = g_369_l;
    *(char *)&g16 = g_378_l;
    *(char *)&g17 = g_379_l;
    g18 = g_456_l;
    g19 = g_526_l;
    *(int16_t *)&g20 = g_527_l;
    *(char *)&g21 = g_534_l;
    *(char *)&g22 = g_566_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3a10 - 0x3a6d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x3a10
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3a70 - 0x3ab0
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g23;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g28); // 0x3aa5
    g23 = v1 / 256 ^ v2;
}

// Address range: 0x3ab0 - 0x3abd
int64_t _fini(void) {
    // 0x3ab0
    int64_t result; // 0x3ab0
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

