//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int32_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_5_l, int32_t g_21_l, int32_t g_22_l, char g_35_l, int32_t g_63_l, int32_t g_65_l, char g_66_l, int16_t g_73_l, int32_t g_90_l, int32_t g_91_l, char g_122_l, int32_t g_136_l, char g_145_l, int32_t g_146_l, int32_t g_147_l, int16_t g_149_l, int32_t g_151_l, int32_t g_153_l, int32_t g_182_l, int32_t g_198_l, int16_t g_229_l, int32_t g_239_l, int16_t g_289_l, int32_t g_306_l, int32_t g_516_l, int32_t g_556_l, int16_t g_633_l, int16_t g_688_l, char g_692_l, int32_t g_694_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1 = -0x1787dbbc; // 0x22dc
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x5fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x5f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g2);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x10b0
    return v1 + 0x5fc3;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x5f2b); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s777r2.c
// Address range: 0x11a0 - 0x166b
// Line range:    454 - 493
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x3e67)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x5e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x3e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x5e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x3e60), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x5ed0); // 0x125e
    transparent_crc(v5, (char *)(v2 + 0x3e64), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x5ed4); // 0x1280
    transparent_crc(v6, (char *)(v2 + 0x3e69), v1);
    unsigned char v7 = *(char *)(v2 + 0x5e70); // 0x12a2
    transparent_crc((int32_t)v7, (char *)(v2 + 0x3e6e), v1);
    int32_t v8 = *(int32_t *)(v2 + 0x5e74); // 0x12c5
    transparent_crc(v8, (char *)(v2 + 0x3e73), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x5e78); // 0x12e7
    transparent_crc(v9, (char *)(v2 + 0x3e78), v1);
    char v10 = *(char *)(v2 + 0x5e7c); // 0x1309
    transparent_crc((int32_t)v10, (char *)(v2 + 0x3e7d), v1);
    uint16_t v11 = *(int16_t *)(v2 + 0x5e7e); // 0x132c
    transparent_crc((int32_t)v11, (char *)(v2 + 0x3e82), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x5e80); // 0x134f
    transparent_crc(v12, (char *)(v2 + 0x3e87), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x5e84); // 0x1371
    transparent_crc(v13, (char *)(v2 + 0x3e8c), v1);
    unsigned char v14 = *(char *)(v2 + 0x5e88); // 0x1393
    transparent_crc((int32_t)v14, (char *)(v2 + 0x3e91), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x5e8c); // 0x13b6
    transparent_crc(v15, (char *)(v2 + 0x3e97), v1);
    char v16 = *(char *)(v2 + 0x5e90); // 0x13d8
    transparent_crc((int32_t)v16, (char *)(v2 + 0x3e9d), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x5ed8); // 0x13fd
    transparent_crc(v17, (char *)(v2 + 0x3ea3), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x5e94); // 0x141f
    transparent_crc(v18, (char *)(v2 + 0x3ea9), v1);
    int16_t v19 = *(int16_t *)(v2 + 0x5e98); // 0x1441
    transparent_crc((int32_t)v19, (char *)(v2 + 0x3eaf), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x5e9c); // 0x1467
    transparent_crc(v20, (char *)(v2 + 0x3eb5), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x5ea0); // 0x1489
    transparent_crc(v21, (char *)(v2 + 0x3ebb), v1);
    int32_t v22 = *(int32_t *)(v2 + 0x5ea4); // 0x14ab
    transparent_crc(v22, (char *)(v2 + 0x3ec1), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x5edc); // 0x14cd
    transparent_crc(v23, (char *)(v2 + 0x3ec7), v1);
    uint16_t v24 = *(int16_t *)(v2 + 0x5ea8); // 0x14ef
    transparent_crc((int32_t)v24, (char *)(v2 + 0x3ecd), v1);
    int32_t v25 = *(int32_t *)(v2 + 0x5eac); // 0x1512
    transparent_crc(v25, (char *)(v2 + 0x3ed3), v1);
    int16_t v26 = *(int16_t *)(v2 + 0x5eb0); // 0x1534
    transparent_crc((int32_t)v26, (char *)(v2 + 0x3ed9), v1);
    int32_t v27 = *(int32_t *)(v2 + 0x5ee0); // 0x1557
    transparent_crc(v27, (char *)(v2 + 0x3edf), v1);
    int32_t v28 = *(int32_t *)(v2 + 0x5eb4); // 0x1579
    transparent_crc(v28, (char *)(v2 + 0x3ee5), v1);
    int32_t v29 = *(int32_t *)(v2 + 0x5eb8); // 0x159b
    transparent_crc(v29, (char *)(v2 + 0x3eeb), v1);
    int16_t v30 = *(int16_t *)(v2 + 0x5ebc); // 0x15bd
    transparent_crc((int32_t)v30, (char *)(v2 + 0x3ef1), v1);
    int16_t v31 = *(int16_t *)(v2 + 0x5ebe); // 0x15e0
    transparent_crc((int32_t)v31, (char *)(v2 + 0x3ef7), v1);
    char v32 = *(char *)(v2 + 0x5ec0); // 0x1606
    transparent_crc((int32_t)v32, (char *)(v2 + 0x3efd), v1);
    int32_t v33 = *(int32_t *)(v2 + 0x5ec4); // 0x1629
    transparent_crc(v33, (char *)(v2 + 0x3f03), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x5ec8), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1670 - 0x1675
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1670
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1680 - 0x1728
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x16fa
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x16c1
        while (v1 != 0) {
            // 0x16c7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1705
        int32_t v5; // 0x1680
        *(int32_t *)(v5 + 0x5a05 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s777r2.c
// Address range: 0x1730 - 0x4c68
// Line range:    68 - 447
int32_t func_1(void) {
    while (true) {
        // continue -> 0x38f6
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4c70 - 0x4ccf
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x4c70
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x4c70
    if (v1 != 0) {
        // 0x4ca4
        printf((char *)(v1 + 1081));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x4cd0 - 0x4d04
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x4cd0
    int32_t v1; // 0x4cd0
    printf((char *)(v1 + 1020));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s777r2.c
// Address range: 0x4d10 - 0x4eaf
// Line range:    58 - 60
int32_t set_var(int32_t g_2_l, int32_t g_5_l, int32_t g_21_l, int32_t g_22_l, char g_35_l, int32_t g_63_l, int32_t g_65_l, char g_66_l, int16_t g_73_l, int32_t g_90_l, int32_t g_91_l, char g_122_l, int32_t g_136_l, char g_145_l, int32_t g_146_l, int32_t g_147_l, int16_t g_149_l, int32_t g_151_l, int32_t g_153_l, int32_t g_182_l, int32_t g_198_l, int16_t g_229_l, int32_t g_239_l, int16_t g_289_l, int32_t g_306_l, int32_t g_516_l, int32_t g_556_l, int16_t g_633_l, int16_t g_688_l, char g_692_l, int32_t g_694_l) {
    // 0x4d10
    int32_t v1; // 0x4d10
    *(int32_t *)(v1 + (int32_t)&g1 + 32) = g_5_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 36) = g_21_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 136) = g_22_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 140) = (int32_t)g_35_l;
    *(char *)(v1 + (int32_t)&g1 + 40) = (char)g_63_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 44) = g_65_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 48) = (int32_t)g_66_l;
    *(char *)(v1 + (int32_t)&g1 + 52) = (char)g_73_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 54) = (int16_t)g_90_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 56) = g_91_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 60) = (int32_t)g_122_l;
    *(char *)(v1 + (int32_t)&g1 + 64) = (char)g_136_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 68) = (int32_t)g_145_l;
    *(char *)(v1 + (int32_t)&g1 + 72) = (char)g_146_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 144) = g_147_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 76) = (int32_t)g_149_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 80) = (int16_t)g_151_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 84) = g_153_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 88) = g_182_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 92) = g_198_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 148) = (int32_t)g_229_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 96) = (int16_t)g_239_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 100) = (int32_t)g_289_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 104) = (int16_t)g_306_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 152) = g_516_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 108) = g_556_l;
    *(int32_t *)(v1 + (int32_t)&g1 + 112) = (int32_t)g_633_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 116) = g_688_l;
    *(int16_t *)(v1 + (int32_t)&g1 + 118) = (int16_t)g_692_l;
    *(char *)(v1 + (int32_t)&g1 + 120) = (char)g_694_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4eb0 - 0x4f30
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x4eb0
    int32_t v1; // 0x4eb0
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4f30 - 0x4f74
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x4f30
    int32_t v1; // 0x4f30
    int32_t * v2 = (int32_t *)(v1 + 0x213b); // 0x4f43
    uint32_t v3 = *v2; // 0x4f43
    char v4; // 0x4f30
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2157 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x4f74 - 0x4f8c
int32_t _fini(void) {
    // 0x4f74
    int32_t v1; // 0x4f74
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

