//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int16_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int16_t g_7_l, int32_t g_13_l, int16_t g_14_l, int32_t g_15_l, int16_t g_32_l, int32_t g_51_l, int16_t g_88_l, int32_t g_108_l, int32_t g_118_l, int32_t g_120_l, int32_t g_151_l, int32_t g_194_l, int16_t g_195_l, int32_t g_211_l, char g_225_l, char g_330_l, char g_341_l, char g_342_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1 = 0x144d8b00; // 0x3048
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g2);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x10b0
    return v1 + 0x4f9f;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f07); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s911retdec.c
// Address range: 0x11a0 - 0x14ab
// Line range:    284 - 310
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2ea6)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int16_t v3 = *(int16_t *)(v2 + 0x4e68); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x2e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x4e6c); // 0x123d
    transparent_crc(v4, (char *)(v2 + 0x2e60), v1);
    uint16_t v5 = *(int16_t *)(v2 + 0x4e70); // 0x125f
    transparent_crc((int32_t)v5, (char *)(v2 + 0x2e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x4e74); // 0x1282
    transparent_crc(v6, (char *)(v2 + 0x2e6a), v1);
    int16_t v7 = *(int16_t *)(v2 + 0x4e78); // 0x12a4
    transparent_crc((int32_t)v7, (char *)(v2 + 0x2e6f), v1);
    int32_t v8 = *(int32_t *)(v2 + 0x4e7c); // 0x12c7
    transparent_crc(v8, (char *)(v2 + 0x2e74), v1);
    int16_t v9 = *(int16_t *)(v2 + 0x4e80); // 0x12e9
    transparent_crc((int32_t)v9, (char *)(v2 + 0x2e79), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x4e84); // 0x130c
    transparent_crc(v10, (char *)(v2 + 0x2e7e), v1);
    int32_t v11 = *(int32_t *)(v2 + 0x4e88); // 0x132e
    transparent_crc(v11, (char *)(v2 + 0x2e84), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x4e8c); // 0x1350
    transparent_crc(v12, (char *)(v2 + 0x2e8a), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e90); // 0x1372
    transparent_crc(v13, (char *)(v2 + 0x2e90), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x4e94); // 0x1394
    transparent_crc(v14, (char *)(v2 + 0x2e96), v1);
    int16_t v15 = *(int16_t *)(v2 + 0x4e98); // 0x13b6
    transparent_crc((int32_t)v15, (char *)(v2 + 0x2e9c), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x4e9c); // 0x13d9
    transparent_crc(v16, (char *)(v2 + 0x2ea2), v1);
    unsigned char v17 = *(char *)(v2 + 0x4ea0); // 0x13fb
    transparent_crc((int32_t)v17, (char *)(v2 + 0x2ea8), v1);
    unsigned char v18 = *(char *)(v2 + 0x4ea1); // 0x141e
    transparent_crc((int32_t)v18, (char *)(v2 + 0x2eae), v1);
    char v19 = *(char *)(v2 + 0x4ea2); // 0x1441
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eb4), v1);
    unsigned char v20 = *(char *)(v2 + 0x4ea3); // 0x1466
    transparent_crc((int32_t)v20, (char *)(v2 + 0x2eba), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4ea4), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x14b0 - 0x14b5
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x14b0
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x14c0 - 0x1568
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x153a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1501
        while (v1 != 0) {
            // 0x1507
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x1545
        int32_t v5; // 0x14c0
        *(int32_t *)(v5 + 0x4b8d + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s911retdec.c
// Address range: 0x1570 - 0x2f3f
// Line range:    59 - 277
int16_t func_1(void) {
    // 0x2dfe
    set_var(-1, -253, -253, 0, -2316, 0x5dd727ab, 0x5a50, -4, -0x590a96, 1, -1, 1, 1, 0x2675de23, -71, 46, 126, 9);
    return 46;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2f40 - 0x2f9f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2f40
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2f40
    if (v1 != 0) {
        // 0x2f74
        printf((char *)(v1 + 0x1120));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x2fa0 - 0x2fd4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2fa0
    int32_t v1; // 0x2fa0
    printf((char *)(v1 + (int32_t)&g1 - 0x1f65));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s911retdec.c
// Address range: 0x2fe0 - 0x30da
// Line range:    49 - 51
int32_t set_var(int16_t g_7_l, int32_t g_13_l, int16_t g_14_l, int32_t g_15_l, int16_t g_32_l, int32_t g_51_l, int16_t g_88_l, int32_t g_108_l, int32_t g_118_l, int32_t g_120_l, int32_t g_151_l, int32_t g_194_l, int16_t g_195_l, int32_t g_211_l, char g_225_l, char g_330_l, char g_341_l, char g_342_l) {
    // 0x2fe0
    int32_t v1; // 0x2fe0
    *(int16_t *)(v1 + 0x302c) = (int16_t)g_13_l;
    *(int32_t *)(v1 + 0x3030) = (int32_t)g_14_l;
    *(int16_t *)(v1 + 0x3034) = (int16_t)g_15_l;
    *(int32_t *)(v1 + 0x3038) = (int32_t)g_32_l;
    *(int16_t *)(v1 + 0x303c) = (int16_t)g_51_l;
    *(int32_t *)(v1 + 0x3040) = (int32_t)g_88_l;
    *(int16_t *)(v1 + 0x3044) = (int16_t)g_108_l;
    *(int32_t *)(v1 + 0x3048) = g_118_l;
    *(int32_t *)(v1 + 0x304c) = g_120_l;
    *(int32_t *)(v1 + 0x3050) = g_151_l;
    *(int32_t *)(v1 + 0x3054) = g_194_l;
    *(int32_t *)(v1 + 0x3058) = (int32_t)g_195_l;
    *(int16_t *)(v1 + 0x305c) = (int16_t)g_211_l;
    *(int32_t *)(v1 + 0x3060) = (int32_t)g_225_l;
    *(char *)(v1 + 0x3064) = g_330_l;
    *(char *)(v1 + 0x3065) = g_341_l;
    *(char *)(v1 + 0x3066) = g_342_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x30e0 - 0x3160
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x30e0
    int32_t v1; // 0x30e0
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3160 - 0x31a4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x3160
    int32_t v1; // 0x3160
    int32_t * v2 = (int32_t *)(v1 + 0x2ee7); // 0x3173
    uint32_t v3 = *v2; // 0x3173
    char v4; // 0x3160
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2eef + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x31a4 - 0x31bc
int32_t _fini(void) {
    // 0x31a4
    int32_t v1; // 0x31a4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

