//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
int16_t func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_10_l, int16_t g_18_l, int32_t g_21_l, int16_t g_26_l, int16_t g_27_l, int32_t g_28_l, int16_t g_36_l, int32_t g_44_l, int32_t g_45_l, int32_t g_54_l, int16_t g_59_l, char g_60_l, int32_t g_102_l, int32_t g_115_l, int32_t g_122_l, int32_t g_125_l, int32_t g_228_l, int32_t g_230_l, int16_t g_231_l, int16_t g_385_l, int16_t g_406_l, int16_t g_427_l, int32_t g_454_l, char g_482_l, int16_t g_522_l, int16_t g_531_l, int32_t g_616_l, char g_633_l, int32_t g_648_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x5fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x5f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x5fbf;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x5f27); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s925retdec.c
// Address range: 0x11a0 - 0x164d
// Line range:    482 - 520
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x3e6d)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    uint16_t v3 = *(int16_t *)(v2 + 0x3f34); // 0x121a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x3e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x5ecc); // 0x1240
    transparent_crc(v4, (char *)(v2 + 0x3e60), v1);
    int16_t v5 = *(int16_t *)(v2 + 0x5e68); // 0x1262
    transparent_crc((int32_t)v5, (char *)(v2 + 0x3e65), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x5e6c); // 0x1285
    transparent_crc(v6, (char *)(v2 + 0x3e6a), v1);
    int16_t v7 = *(int16_t *)(v2 + 0x5e70); // 0x12a7
    transparent_crc((int32_t)v7, (char *)(v2 + 0x3e6f), v1);
    int16_t v8 = *(int16_t *)(v2 + 0x5e72); // 0x12cd
    transparent_crc((int32_t)v8, (char *)(v2 + 0x3e74), v1);
    int32_t v9 = *(int32_t *)(v2 + 0x5e74); // 0x12f0
    transparent_crc(v9, (char *)(v2 + 0x3e79), v1);
    int16_t v10 = *(int16_t *)(v2 + 0x5e78); // 0x1312
    transparent_crc((int32_t)v10, (char *)(v2 + 0x3e7e), v1);
    int32_t v11 = *(int32_t *)(v2 + 0x5e7c); // 0x1335
    transparent_crc(v11, (char *)(v2 + 0x3e83), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x5e80); // 0x1357
    transparent_crc(v12, (char *)(v2 + 0x3e88), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x5e84); // 0x1379
    transparent_crc(v13, (char *)(v2 + 0x3e8d), v1);
    uint16_t v14 = *(int16_t *)(v2 + 0x5e88); // 0x139b
    transparent_crc((int32_t)v14, (char *)(v2 + 0x3e92), v1);
    unsigned char v15 = *(char *)(v2 + 0x5e8a); // 0x13be
    transparent_crc((int32_t)v15, (char *)(v2 + 0x3e97), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x5e8c); // 0x13e1
    transparent_crc(v16, (char *)(v2 + 0x3e9c), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x5e90); // 0x1403
    transparent_crc(v17, (char *)(v2 + 0x3ea2), v1);
    int32_t v18 = *(int32_t *)(v2 + 0x5e94); // 0x1425
    transparent_crc(v18, (char *)(v2 + 0x3ea8), v1);
    int32_t v19 = *(int32_t *)(v2 + 0x5e98); // 0x1447
    transparent_crc(v19, (char *)(v2 + 0x3eae), v1);
    int32_t v20 = *(int32_t *)(v2 + 0x5e9c); // 0x1469
    transparent_crc(v20, (char *)(v2 + 0x3eb4), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x5ea0); // 0x148b
    transparent_crc(v21, (char *)(v2 + 0x3eba), v1);
    uint16_t v22 = *(int16_t *)(v2 + 0x5ea4); // 0x14ad
    transparent_crc((int32_t)v22, (char *)(v2 + 0x3ec0), v1);
    int16_t v23 = *(int16_t *)(v2 + 0x5ea6); // 0x14d0
    transparent_crc((int32_t)v23, (char *)(v2 + 0x3ec6), v1);
    uint16_t v24 = *(int16_t *)(v2 + 0x5ea8); // 0x14f3
    transparent_crc((int32_t)v24, (char *)(v2 + 0x3ecc), v1);
    uint16_t v25 = *(int16_t *)(v2 + 0x5eaa); // 0x1516
    transparent_crc((int32_t)v25, (char *)(v2 + 0x3ed2), v1);
    int32_t v26 = *(int32_t *)(v2 + 0x5eac); // 0x1539
    transparent_crc(v26, (char *)(v2 + 0x3ed8), v1);
    char v27 = *(char *)(v2 + 0x5eb0); // 0x155b
    transparent_crc((int32_t)v27, (char *)(v2 + 0x3ede), v1);
    int16_t v28 = *(int16_t *)(v2 + 0x5eb2); // 0x157e
    transparent_crc((int32_t)v28, (char *)(v2 + 0x3ee4), v1);
    uint16_t v29 = *(int16_t *)(v2 + 0x5eb4); // 0x15a1
    transparent_crc((int32_t)v29, (char *)(v2 + 0x3eea), v1);
    int32_t v30 = *(int32_t *)(v2 + 0x5eb8); // 0x15c4
    transparent_crc(v30, (char *)(v2 + 0x3ef0), v1);
    unsigned char v31 = *(char *)(v2 + 0x5ebc); // 0x15e6
    transparent_crc((int32_t)v31, (char *)(v2 + 0x3ef6), v1);
    int32_t v32 = *(int32_t *)(v2 + 0x5ec0); // 0x160b
    transparent_crc(v32, (char *)(v2 + 0x3efc), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x5ec4), v1);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1650 - 0x1655
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1650
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1660 - 0x1708
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x16da
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x16a1
        while (v1 != 0) {
            // 0x16a7
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x16e5
        int32_t v5; // 0x1660
        *(int32_t *)(v5 + 0x5a11 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s925retdec.c
// Address range: 0x1710 - 0x4c06
// Line range:    71 - 475
int16_t func_1(void) {
    // 0x1710
    set_var(0, 0x2fcb, 0, -3243, 0x5daa, -0x77c7ff6b, 0x2fcb, -6, -10, 1, -0x2fc3, -82, -1, 1, -1, -0x20883403, -0x1eda867d, 1, 179, 0x2620, 1, -0x51a4, 0x64c719aa, -9, -0x233e, -5, -0x14312330, -85, 0x3510a282);
    return 1;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4c10 - 0x4c6f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x4c10
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x4c10
    if (v1 != 0) {
        // 0x4c44
        printf((char *)(v1 + 1170));
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x4c70 - 0x4ca4
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x4c70
    int32_t v1; // 0x4c70
    printf((char *)(v1 + 1109));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s925retdec.c
// Address range: 0x4cb0 - 0x4e40
// Line range:    61 - 63
int32_t set_var(int32_t g_10_l, int16_t g_18_l, int32_t g_21_l, int16_t g_26_l, int16_t g_27_l, int32_t g_28_l, int16_t g_36_l, int32_t g_44_l, int32_t g_45_l, int32_t g_54_l, int16_t g_59_l, char g_60_l, int32_t g_102_l, int32_t g_115_l, int32_t g_122_l, int32_t g_125_l, int32_t g_228_l, int32_t g_230_l, int16_t g_231_l, int16_t g_385_l, int16_t g_406_l, int16_t g_427_l, int32_t g_454_l, char g_482_l, int16_t g_522_l, int16_t g_531_l, int32_t g_616_l, char g_633_l, int32_t g_648_l) {
    // 0x4cb0
    int32_t v1; // 0x4cb0
    *(int32_t *)(v1 + 0x23c0) = (int32_t)g_18_l;
    *(int16_t *)(v1 + 0x235c) = (int16_t)g_21_l;
    *(int32_t *)(v1 + 0x2360) = (int32_t)g_26_l;
    *(int16_t *)(v1 + 0x2364) = g_27_l;
    *(int16_t *)(v1 + 0x2366) = (int16_t)g_28_l;
    *(int32_t *)(v1 + 0x2368) = (int32_t)g_36_l;
    *(int16_t *)(v1 + 0x236c) = (int16_t)g_44_l;
    *(int32_t *)(v1 + 0x2370) = g_45_l;
    *(int32_t *)(v1 + 0x2374) = g_54_l;
    *(int32_t *)(v1 + 0x2378) = (int32_t)g_59_l;
    *(int16_t *)(v1 + 0x237c) = (int16_t)g_60_l;
    *(char *)(v1 + 0x237e) = (char)g_102_l;
    *(int32_t *)(v1 + 0x2380) = g_115_l;
    *(int32_t *)(v1 + 0x2384) = g_122_l;
    *(int32_t *)(v1 + 0x2388) = g_125_l;
    *(int32_t *)(v1 + 0x238c) = g_228_l;
    *(int32_t *)(v1 + 0x2390) = g_230_l;
    *(int32_t *)(v1 + 0x2394) = (int32_t)g_231_l;
    *(int16_t *)(v1 + 0x2398) = g_385_l;
    *(int16_t *)(v1 + 0x239a) = g_406_l;
    *(int16_t *)(v1 + 0x239c) = g_427_l;
    *(int16_t *)(v1 + 0x239e) = (int16_t)g_454_l;
    *(int32_t *)(v1 + 0x23a0) = (int32_t)g_482_l;
    *(char *)(v1 + 0x23a4) = (char)g_522_l;
    *(int16_t *)(v1 + 0x23a6) = g_531_l;
    *(int16_t *)(v1 + 0x23a8) = (int16_t)g_616_l;
    *(int32_t *)(v1 + 0x23ac) = (int32_t)g_633_l;
    *(char *)(v1 + 0x23b0) = (char)g_648_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4e40 - 0x4ec0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x4e40
    int32_t v1; // 0x4e40
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x4ec0 - 0x4f04
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x4ec0
    int32_t v1; // 0x4ec0
    int32_t * v2 = (int32_t *)(v1 + 0x21a7); // 0x4ed3
    uint32_t v3 = *v2; // 0x4ed3
    char v4; // 0x4ec0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x21b3 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x4f04 - 0x4f1c
int32_t _fini(void) {
    // 0x4f04
    int32_t v1; // 0x4f04
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

