//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int16_t g_13_l, int32_t g_14_l, int32_t g_32_l, int32_t g_38_l, int32_t g_41_l, int16_t g_58_l, char g_85_l, char g_87_l, char g_95_l, int32_t g_96_l, int32_t g_98_l, int32_t g_99_l, int32_t g_103_l, int32_t g_109_l, char g_150_l, int16_t g_159_l, int16_t g_160_l, int16_t g_162_l, int32_t g_206_l, int32_t g_207_l, int32_t g_208_l, char g_211_l, char g_212_l, char g_213_l, int32_t g_214_l, int16_t g_215_l, int32_t g_242_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10b0
    return v1 + 0x4fb3;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f1b); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s951r2.c
// Address range: 0x11a0 - 0x1629
// Line range:    267 - 304
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2edc)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc(1, (char *)(v2 + 0x2e5c), v1);
    uint16_t v3 = *(int16_t *)(v2 + 0x4e68); // 0x123a
    transparent_crc((int32_t)v3, (char *)(v2 + 0x2e60), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x4e6c); // 0x125d
    transparent_crc(v4, (char *)(v2 + 0x2e65), v1);
    int32_t v5 = *(int32_t *)(v2 + 0x4ec0); // 0x127f
    transparent_crc(v5, (char *)(v2 + 0x2e6a), v1);
    int32_t v6 = *(int32_t *)(v2 + 0x4e70); // 0x12a1
    transparent_crc(v6, (char *)(v2 + 0x2e6f), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x4e74); // 0x12c3
    transparent_crc(v7, (char *)(v2 + 0x2e74), v1);
    int16_t v8 = *(int16_t *)(v2 + 0x4e78); // 0x12e5
    transparent_crc((int32_t)v8, (char *)(v2 + 0x2e79), v1);
    unsigned char v9 = *(char *)(v2 + 0x4e7a); // 0x1308
    transparent_crc((int32_t)v9, (char *)(v2 + 0x2e7e), v1);
    unsigned char v10 = *(char *)(v2 + 0x4e7b); // 0x132b
    transparent_crc((int32_t)v10, (char *)(v2 + 0x2e83), v1);
    char v11 = *(char *)(v2 + 0x4e7c); // 0x134e
    transparent_crc((int32_t)v11, (char *)(v2 + 0x2e88), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x4e80); // 0x1371
    transparent_crc(v12, (char *)(v2 + 0x2e8d), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e84); // 0x1393
    transparent_crc(v13, (char *)(v2 + 0x2e92), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x4e88); // 0x13b5
    transparent_crc(v14, (char *)(v2 + 0x2e97), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x4e8c); // 0x13d7
    transparent_crc(v15, (char *)(v2 + 0x2e9c), v1);
    int32_t v16 = *(int32_t *)(v2 + 0x4e90); // 0x13f9
    transparent_crc(v16, (char *)(v2 + 0x2ea2), v1);
    char v17 = *(char *)(v2 + 0x4e94); // 0x141b
    transparent_crc((int32_t)v17, (char *)(v2 + 0x2ea8), v1);
    int16_t v18 = *(int16_t *)(v2 + 0x4e96); // 0x1440
    transparent_crc((int32_t)v18, (char *)(v2 + 0x2eae), v1);
    int16_t v19 = *(int16_t *)(v2 + 0x4e98); // 0x1466
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eb4), v1);
    uint16_t v20 = *(int16_t *)(v2 + 0x4ec4); // 0x1489
    transparent_crc((int32_t)v20, (char *)(v2 + 0x2eba), v1);
    transparent_crc(0, (char *)(v2 + 0x2ec0), v1);
    int32_t v21 = *(int32_t *)(v2 + 0x4e9c); // 0x14d1
    transparent_crc(v21, (char *)(v2 + 0x2ec6), v1);
    int32_t v22 = *(int32_t *)(v2 + 0x4ea0); // 0x14f3
    transparent_crc(v22, (char *)(v2 + 0x2ecc), v1);
    int32_t v23 = *(int32_t *)(v2 + 0x4ea4); // 0x1515
    transparent_crc(v23, (char *)(v2 + 0x2ed2), v1);
    char v24 = *(char *)(v2 + 0x4ea8); // 0x1537
    transparent_crc((int32_t)v24, (char *)(v2 + 0x2ed8), v1);
    char v25 = *(char *)(v2 + 0x4ea9); // 0x155a
    transparent_crc((int32_t)v25, (char *)(v2 + 0x2ede), v1);
    char v26 = *(char *)(v2 + 0x4eaa); // 0x157d
    transparent_crc((int32_t)v26, (char *)(v2 + 0x2ee4), v1);
    int32_t v27 = *(int32_t *)(v2 + 0x4eac); // 0x15a2
    transparent_crc(v27, (char *)(v2 + 0x2eea), v1);
    uint16_t v28 = *(int16_t *)(v2 + 0x4eb0); // 0x15c4
    transparent_crc((int32_t)v28, (char *)(v2 + 0x2ef0), v1);
    int32_t v29 = *(int32_t *)(v2 + 0x4eb4); // 0x15e7
    transparent_crc(v29, (char *)(v2 + 0x2ef6), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4eb8), v1);
    return 0;
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x1630 - 0x1635
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1630
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1640 - 0x16e8
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x16ba
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1681
        while (v1 != 0) {
            // 0x1687
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x16c5
        int32_t v5; // 0x1640
        *(int32_t *)(v5 + 0x4a29 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s951r2.c
// Address range: 0x16f0 - 0x2edb
// Line range:    70 - 260
char func_1(void) {
    // 0x16f0
    set_var(0x7255, -26, 0, 0x783de769, 0x5d3e8ea4, 1, -72, 1, -77, -1, -0x47e38b0e, -11, -7, -1, -6, 0x690d, -1, 0, 4, -0x6132ad2f, -1, 104, -64, -103, 1, -0x5271, 6);
    return -92;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2ee0 - 0x2f3f
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x2ee0
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x2ee0
    if (v1 != 0) {
        // 0x2f14
        printf((char *)(v1 + 0x11bc));
    }
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x2f40 - 0x2f74
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2f40
    int32_t v1; // 0x2f40
    printf((char *)(v1 + 0x117f));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s951r2.c
// Address range: 0x2f80 - 0x30e9
// Line range:    60 - 62
int32_t set_var(int16_t g_13_l, int32_t g_14_l, int32_t g_32_l, int32_t g_38_l, int32_t g_41_l, int16_t g_58_l, char g_85_l, char g_87_l, char g_95_l, int32_t g_96_l, int32_t g_98_l, int32_t g_99_l, int32_t g_103_l, int32_t g_109_l, char g_150_l, int16_t g_159_l, int16_t g_160_l, int16_t g_162_l, int32_t g_206_l, int32_t g_207_l, int32_t g_208_l, char g_211_l, char g_212_l, char g_213_l, int32_t g_214_l, int16_t g_215_l, int32_t g_242_l) {
    // 0x2f80
    int32_t v1; // 0x2f80
    *(int16_t *)(v1 + 0x308c) = (int16_t)g_14_l;
    *(int32_t *)(v1 + 0x3090) = g_32_l;
    *(int32_t *)(v1 + 0x30e4) = g_38_l;
    *(int32_t *)(v1 + 0x3094) = g_41_l;
    *(int32_t *)(v1 + 0x3098) = (int32_t)g_58_l;
    *(int16_t *)(v1 + 0x309c) = (int16_t)g_85_l;
    *(char *)(v1 + 0x309e) = g_87_l;
    *(char *)(v1 + 0x309f) = g_95_l;
    *(char *)(v1 + 0x30a0) = (char)g_96_l;
    *(int32_t *)(v1 + 0x30a4) = g_98_l;
    *(int32_t *)(v1 + 0x30a8) = g_99_l;
    *(int32_t *)(v1 + 0x30ac) = g_103_l;
    *(int32_t *)(v1 + 0x30b0) = g_109_l;
    *(int32_t *)(v1 + 0x30b4) = (int32_t)g_150_l;
    *(char *)(v1 + 0x30b8) = (char)g_159_l;
    *(int16_t *)(v1 + 0x30ba) = g_160_l;
    *(int16_t *)(v1 + 0x30bc) = g_162_l;
    *(int16_t *)(v1 + 0x30e8) = (int16_t)g_206_l;
    *(int32_t *)(v1 + 0x30c0) = g_207_l;
    *(int32_t *)(v1 + 0x30c4) = g_208_l;
    *(int32_t *)(v1 + 0x30c8) = (int32_t)g_211_l;
    *(char *)(v1 + 0x30cc) = g_212_l;
    *(char *)(v1 + 0x30cd) = g_213_l;
    *(char *)(v1 + 0x30ce) = (char)g_214_l;
    *(int32_t *)(v1 + 0x30d0) = (int32_t)g_215_l;
    *(int16_t *)(v1 + 0x30d4) = (int16_t)g_242_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x30f0 - 0x3170
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x30f0
    int32_t v1; // 0x30f0
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3170 - 0x31b4
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x3170
    int32_t v1; // 0x3170
    int32_t * v2 = (int32_t *)(v1 + 0x2eeb); // 0x3183
    uint32_t v3 = *v2; // 0x3183
    char v4; // 0x3170
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2efb + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x31b4 - 0x31cc
int32_t _fini(void) {
    // 0x31b4
    int32_t v1; // 0x31b4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

