//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
void crc32_8bytes(int32_t val);
void crc32_byte(char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_109c(int32_t a1);
int32_t function_10b0(void);
int32_t function_10f0(void);
int32_t function_1140(void);
int32_t function_1190(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(int32_t g_2_l, int32_t g_5_l, int16_t g_23_l, char g_31_l, int32_t g_51_l, int16_t g_52_l, char g_80_l, int32_t g_144_l, char g_188_l, int32_t g_202_l, int32_t g_204_l, int32_t g_269_l, int32_t g_283_l, char g_288_l, int32_t g_326_l, int16_t g_364_l, int16_t g_379_l, char g_380_l, int16_t g_444_l, int32_t g_456_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int16_t g1 = 0x2444; // 0x1323
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x4fdb);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x109c
int32_t _start(int32_t a1) {
    // 0x1070
    int32_t v1; // 0x1070
    function_109c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x4f68); // 0x1090
    int32_t v3; // 0x1070
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g2);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x109c - 0x10a0
int32_t function_109c(int32_t a1) {
    // 0x109c
    int32_t result; // 0x109c
    return result;
}

// Address range: 0x10a0 - 0x10a4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10a0
    int32_t result; // 0x10a0
    return result;
}

// Address range: 0x10b0 - 0x10e9
int32_t function_10b0(void) {
    // 0x10b0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    int32_t v1; // 0x10b0
    return v1 + 0x4f9f;
}

// Address range: 0x10f0 - 0x1137
int32_t function_10f0(void) {
    // 0x10f0
    __x86_get_pc_thunk_dx((int32_t)&g2);
    return 0;
}

// Address range: 0x1140 - 0x118c
int32_t function_1140(void) {
    // 0x1140
    int32_t v1; // 0x1140
    int32_t v2 = __x86_get_pc_thunk_bx(v1); // 0x1148
    char * v3 = (char *)(v1 + 0x4f07); // 0x1156
    int32_t result = v2; // 0x115d
    if (*v3 == 0) {
        // 0x115f
        result = function_10b0();
        *v3 = 1;
    }
    // 0x1187
    return result;
}

// Address range: 0x1190 - 0x1199
int32_t function_1190(void) {
    // 0x1190
    return function_10f0();
}

// Address range: 0x1199 - 0x119d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1199
    int32_t result; // 0x1199
    return result;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s965r2.c
// Address range: 0x11a0 - 0x150e
// Line range:    372 - 401
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x11ce
    int32_t v2; // 0x11a0
    if (argv == (char **)2) {
        int32_t str = *(int32_t *)(v2 + 4); // 0x11da
        v1 = strcmp((char *)str, (char *)(v2 + 0x2e6c)) == 0;
    }
    // 0x11ff
    platform_main_begin();
    crc32_gentab();
    func_1();
    int32_t v3 = *(int32_t *)(v2 + 0x4e68); // 0x121a
    transparent_crc(v3, (char *)(v2 + 0x2e5c), v1);
    int32_t v4 = *(int32_t *)(v2 + 0x4e6c); // 0x123c
    transparent_crc(v4, (char *)(v2 + 0x2e60), v1);
    uint16_t v5 = *(int16_t *)(v2 + 0x4e70); // 0x125e
    transparent_crc((int32_t)v5, (char *)(v2 + 0x2e64), v1);
    unsigned char v6 = *(char *)(v2 + 0x4e72); // 0x1281
    transparent_crc((int32_t)v6, (char *)(v2 + 0x2e69), v1);
    int32_t v7 = *(int32_t *)(v2 + 0x4e74); // 0x12a4
    transparent_crc(v7, (char *)(v2 + 0x2e6e), v1);
    int16_t v8 = *(int16_t *)(v2 + 0x4e78); // 0x12c6
    transparent_crc((int32_t)v8, (char *)(v2 + 0x2e73), v1);
    unsigned char v9 = *(char *)(v2 + 0x4e7a); // 0x12e9
    transparent_crc((int32_t)v9, (char *)(v2 + 0x2e78), v1);
    int32_t v10 = *(int32_t *)(v2 + 0x4e7c); // 0x130c
    transparent_crc(v10, (char *)(v2 + 0x2e7d), v1);
    char v11 = *(char *)(v2 + 0x4e80); // 0x132e
    transparent_crc((int32_t)v11, (char *)(v2 + 0x2e83), v1);
    int32_t v12 = *(int32_t *)(v2 + 0x4e84); // 0x1351
    transparent_crc(v12, (char *)(v2 + 0x2e89), v1);
    int32_t v13 = *(int32_t *)(v2 + 0x4e88); // 0x1373
    transparent_crc(v13, (char *)(v2 + 0x2e8f), v1);
    int32_t v14 = *(int32_t *)(v2 + 0x4e8c); // 0x1395
    transparent_crc(v14, (char *)(v2 + 0x2e95), v1);
    int32_t v15 = *(int32_t *)(v2 + 0x4e90); // 0x13b7
    transparent_crc(v15, (char *)(v2 + 0x2e9b), v1);
    unsigned char v16 = *(char *)(v2 + 0x4e94); // 0x13d9
    transparent_crc((int32_t)v16, (char *)(v2 + 0x2ea1), v1);
    transparent_crc(3, (char *)(v2 + 0x2ea7), v1);
    int32_t v17 = *(int32_t *)(v2 + 0x4eac); // 0x141e
    transparent_crc(v17, (char *)(v2 + 0x2ead), v1);
    int16_t v18 = *(int16_t *)(v2 + 0x4e96); // 0x1440
    transparent_crc((int32_t)v18, (char *)(v2 + 0x2eb3), v1);
    int16_t v19 = *(int16_t *)(v2 + 0x4e98); // 0x1463
    transparent_crc((int32_t)v19, (char *)(v2 + 0x2eb9), v1);
    unsigned char v20 = *(char *)(v2 + 0x4e9a); // 0x1486
    transparent_crc((int32_t)v20, (char *)(v2 + 0x2ebf), v1);
    int16_t v21 = *(int16_t *)(v2 + 0x4e9c); // 0x14a9
    transparent_crc((int32_t)v21, (char *)(v2 + 0x2ec5), v1);
    int32_t v22 = *(int32_t *)(v2 + 0x4ea0); // 0x14cc
    transparent_crc(v22, (char *)(v2 + 0x2ecb), v1);
    platform_main_end(-1 - *(int32_t *)(v2 + 0x4ea4), v1);
    return 0;
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x1510 - 0x1515
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1510
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1520 - 0x15c8
// Line range:    58 - 75
void crc32_gentab(void) {
    for (int32_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x159a
        uint32_t v2 = i / 2;
        int32_t v3 = i % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
        v1--;
        int32_t v4 = v3; // 0x1561
        while (v1 != 0) {
            // 0x1567
            v2 = v4 / 2;
            v3 = v4 % 2 == 0 ? v2 : v2 ^ -0x12477ce0;
            v1--;
            v4 = v3;
        }
        // 0x15a5
        int32_t v5; // 0x1520
        *(int32_t *)(v5 + 0x4b31 + 4 * i) = v3;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s965r2.c
// Address range: 0x15d0 - 0x3490
// Line range:    62 - 365
char func_1(void) {
    // 0x16b0
    set_var(0, 1, 0x5352, -22, -0x3dd08b9, -4, -62, -2, 9, -0x95224f7, 0x12bbb44e, 0x91fa, 0x68921b15, -57, 0, -0x5d60, -0x79ac, 44, (int16_t)&g1, -0x6d6eb46e);
    return -110;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3490 - 0x34ef
// Line range:    95 - 101
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x3490
    crc32_8bytes((int32_t)vname);
    int32_t v1; // 0x3490
    if (v1 != 0) {
        // 0x34c4
        printf((char *)(v1 + 3041));
    }
}

// From module:   /usr/include/bits/csmith.h
// Address range: 0x34f0 - 0x3524
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x34f0
    int32_t v1; // 0x34f0
    printf((char *)(v1 + 2980));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s965r2.c
// Address range: 0x3530 - 0x3642
// Line range:    52 - 54
int32_t set_var(int32_t g_2_l, int32_t g_5_l, int16_t g_23_l, char g_31_l, int32_t g_51_l, int16_t g_52_l, char g_80_l, int32_t g_144_l, char g_188_l, int32_t g_202_l, int32_t g_204_l, int32_t g_269_l, int32_t g_283_l, char g_288_l, int32_t g_326_l, int16_t g_364_l, int16_t g_379_l, char g_380_l, int16_t g_444_l, int32_t g_456_l) {
    // 0x3530
    int32_t v1; // 0x3530
    *(int32_t *)(v1 + 0x2adc) = g_5_l;
    *(int32_t *)(v1 + 0x2ae0) = (int32_t)g_23_l;
    *(int16_t *)(v1 + 0x2ae4) = (int16_t)g_31_l;
    *(char *)(v1 + 0x2ae6) = (char)g_51_l;
    *(int32_t *)(v1 + 0x2ae8) = (int32_t)g_52_l;
    *(int16_t *)(v1 + 0x2aec) = (int16_t)g_80_l;
    *(char *)(v1 + 0x2aee) = (char)g_144_l;
    *(int32_t *)(v1 + 0x2af0) = (int32_t)g_188_l;
    *(char *)(v1 + 0x2af4) = (char)g_202_l;
    *(int32_t *)(v1 + 0x2af8) = g_204_l;
    *(int32_t *)(v1 + 0x2afc) = g_269_l;
    *(int32_t *)(v1 + 0x2b00) = g_283_l;
    *(int32_t *)(v1 + 0x2b04) = (int32_t)g_288_l;
    *(char *)(v1 + 0x2b08) = (char)g_326_l;
    *(int32_t *)(v1 + 0x2b20) = (int32_t)g_364_l;
    *(int16_t *)(v1 + 0x2b0a) = g_379_l;
    *(int16_t *)(v1 + 0x2b0c) = (int16_t)g_380_l;
    *(char *)(v1 + 0x2b0e) = (char)g_444_l;
    *(int16_t *)(v1 + 0x2b10) = (int16_t)g_456_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x3650 - 0x36d0
// Line range:    86 - 92
void crc32_8bytes(int32_t val) {
    // 0x3650
    int32_t v1; // 0x3650
    uint32_t v2 = v1;
    crc32_byte((char)v2);
    crc32_byte((char)(v2 / 256));
    crc32_byte((char)(v2 / 0x10000));
    crc32_byte((char)(v2 / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x36d0 - 0x3714
// Line range:    78 - 82
void crc32_byte(char b) {
    // 0x36d0
    int32_t v1; // 0x36d0
    int32_t * v2 = (int32_t *)(v1 + 0x2977); // 0x36e3
    uint32_t v3 = *v2; // 0x36e3
    char v4; // 0x36d0
    *v2 = v3 / 256 ^ *(int32_t *)(v1 + 0x2983 + 4 * (v3 % 256 ^ (int32_t)v4));
}

// Address range: 0x3714 - 0x372c
int32_t _fini(void) {
    // 0x3714
    int32_t v1; // 0x3714
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 22

