//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
void crc32_8bytes(uint32_t val);
void crc32_byte(unsigned char b);
void crc32_gentab(void);
char func_1(void);
int32_t function_1030(char * format, ...);
int32_t function_1040(char * s1, char * s2);
int64_t function_1080(void);
int64_t function_10b0(void);
int64_t function_10f0(void);
int64_t function_1140(void);
void platform_main_begin(void);
void platform_main_end(int32_t crc, int32_t flag);
int32_t set_var(char g_8_l, char g_9_l, int32_t g_29_l, int32_t g_31_l, int32_t g_35_l, int32_t g_47_l, int32_t g_48_l, char g_49_l, char g_70_l, char g_71_l, int16_t g_90_l, int32_t g_106_l, char g_107_l, char g_108_l, char g_109_l, char g_111_l, int16_t g_191_l, int32_t g_192_l, int32_t g_193_l, int32_t g_194_l, int32_t g_195_l, int32_t g_203_l, char g_237_l, int32_t g_273_l, int16_t g_274_l, int32_t g_291_l, int32_t g_297_l, char g_298_l);
void transparent_crc(int32_t val, char * vname, int32_t flag);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4fe0
int32_t g2 = 261; // 0x5020
int32_t g3 = 0x32000001; // 0x5021
int32_t g4 = -0x26bfcece; // 0x5024
int32_t g5 = 3; // 0x5028
int32_t g6 = -0x51534d2b; // 0x502c
int32_t g7 = 0x2b6367af; // 0x5030
int32_t g8 = -1; // 0x5034
int32_t g9 = 0x4afba3; // 0x5038
int32_t g10 = 0x1004afb; // 0x5039
int32_t g11 = 0x1004a; // 0x503a
int32_t g12 = 1; // 0x503c
int32_t g13 = -0x43618cd0; // 0x5040
int32_t g14 = 0x6017ffc; // 0x5044
char g15 = 127; // 0x5045
char g16 = 1; // 0x5046
int32_t g17 = 0xf89a06; // 0x5047
int16_t g18 = -1894; // 0x5048
int32_t g19 = 0x1f61fbc8; // 0x504c
int32_t g20 = 0x558e2862; // 0x5050
int32_t g21 = 1; // 0x5054
int32_t g22 = -1; // 0x5058
int32_t g23 = 0xa42c73b; // 0x505c
int32_t g24 = -1; // 0x5060
int32_t g25 = 0x69775cc2; // 0x5064
int32_t g26 = 96; // 0x5068
int32_t g27 = -1; // 0x506c
int64_t g28 = 0; // 0x5070
int32_t g29 = 0; // 0x5080
int16_t g30 = 0; // 0x5082
int32_t g31 = 0; // 0x5084
int32_t * g32 = NULL; // 0x5090
int32_t g33;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4fd0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g33;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int32_t function_1030(char * format, ...) {
    // 0x1030
    return printf(format);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1076
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1050
    int64_t v1; // 0x1050
    __libc_start_main(0x1150, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1080 - 0x10a9
int64_t function_1080(void) {
    // 0x1080
    return &g28;
}

// Address range: 0x10b0 - 0x10e9
int64_t function_10b0(void) {
    // 0x10b0
    return 0;
}

// Address range: 0x10f0 - 0x1131
int64_t function_10f0(void) {
    // 0x10f0
    if (*(char *)&g28 != 0) {
        // 0x1130
        int64_t result; // 0x10f0
        return result;
    }
    // 0x10fd
    if (g1 != 0) {
        // 0x110b
        __cxa_finalize((int64_t *)*(int64_t *)0x5018);
    }
    int64_t result2 = function_1080(); // 0x1118
    *(char *)&g28 = 1;
    return result2;
}

// Address range: 0x1140 - 0x1149
int64_t function_1140(void) {
    // 0x1140
    return function_10b0();
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s987retdec.c
// Address range: 0x1150 - 0x1433
// Line range:    260 - 296
int main(int argc, char ** argv) {
    int32_t v1 = 0; // 0x1171
    if (argc == 2) {
        int64_t str = *(int64_t *)((int64_t)argv + 8); // 0x117b
        v1 = strcmp((char *)str, "1") == 0;
    }
    // 0x119b
    platform_main_begin();
    crc32_gentab();
    func_1();
    transparent_crc((int32_t)*(char *)&g2, "g_8", v1);
    transparent_crc((int32_t)*(char *)&g3, "g_9", v1);
    transparent_crc(g4, "g_29", v1);
    transparent_crc(g5, "g_31", v1);
    transparent_crc(g6, "g_35", v1);
    transparent_crc(g7, "g_47", v1);
    transparent_crc(g8, "g_48", v1);
    transparent_crc((int32_t)*(char *)&g9, "g_49", v1);
    transparent_crc((int32_t)*(char *)&g10, "g_70", v1);
    transparent_crc((int32_t)*(char *)&g11, "g_71", v1);
    transparent_crc((int32_t)*(int16_t *)&g12, "g_90", v1);
    transparent_crc(g13, "g_106", v1);
    transparent_crc((int32_t)*(char *)&g14, "g_107", v1);
    transparent_crc((int32_t)g15, "g_108", v1);
    transparent_crc((int32_t)g16, "g_109", v1);
    transparent_crc((int32_t)*(char *)&g17, "g_111", v1);
    transparent_crc((int32_t)g18, "g_191", v1);
    transparent_crc(g19, "g_192", v1);
    transparent_crc(g20, "g_193", v1);
    transparent_crc(g21, "g_194", v1);
    transparent_crc(g22, "g_195", v1);
    transparent_crc(g23, "g_203", v1);
    transparent_crc((int32_t)*(char *)&g29, "g_237", v1);
    transparent_crc(g24, "g_273", v1);
    transparent_crc((int32_t)g30, "g_274", v1);
    transparent_crc(g25, "g_291", v1);
    transparent_crc(g31, "g_297", v1);
    transparent_crc((int32_t)*(char *)&g26, "g_298", v1);
    platform_main_end(-1 - *(int32_t *)0x506c, v1);
    return (int32_t)&g33 ^ (int32_t)&g33;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x1440 - 0x1446
// Line range:    43 - 46
void platform_main_begin(void) {
    // 0x1440
    return;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x1450 - 0x14e5
// Line range:    57 - 74
void crc32_gentab(void) {
    for (int64_t i = 0; i < 256; i++) {
        int32_t v1 = 8; // 0x14b9
        int32_t v2 = i; // 0x1450
        uint32_t v3 = v2 / 2;
        int32_t v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
        v1--;
        v2 = v4;
        while (v1 != 0) {
            // 0x1486
            v3 = v2 / 2;
            v4 = v2 % 2 == 0 ? v3 : v3 ^ -0x12477ce0;
            v1--;
            v2 = v4;
        }
        // 0x14c4
        *(int32_t *)(4 * i + (int64_t)&g32) = v4;
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s987retdec.c
// Address range: 0x14f0 - 0x29b1
// Line range:    69 - 253
char func_1(void) {
    // 0x14f0
    set_var(5, 1, -0x26bfcece, 3, -1, 255, -1, -93, -5, 74, 1, -0x43618cd0, 38, 127, 1, 6, -1894, 0x1f61fbc8, 255, 1, -1, 0xa42c73b, 0, -1, -1, 0x69775cc2, -1, 97);
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x29c0 - 0x2a05
// Line range:    94 - 100
void transparent_crc(int32_t val, char * vname, int32_t flag) {
    // 0x29c0
    crc32_8bytes(val);
    if (flag != 0) {
        // 0x29e4
        printf("...checksum after hashing %s : %X\n", vname, -1 - g27);
    }
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-intn.h
// Address range: 0x2a10 - 0x2a35
// Line range:    49 - 120
void platform_main_end(int32_t crc, int32_t flag) {
    // 0x2a10
    printf("checksum = %X\n", crc);
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/seed_all/s987retdec.c
// Address range: 0x2a40 - 0x2be3
// Line range:    59 - 61
int32_t set_var(char g_8_l, char g_9_l, int32_t g_29_l, int32_t g_31_l, int32_t g_35_l, int32_t g_47_l, int32_t g_48_l, char g_49_l, char g_70_l, char g_71_l, int16_t g_90_l, int32_t g_106_l, char g_107_l, char g_108_l, char g_109_l, char g_111_l, int16_t g_191_l, int32_t g_192_l, int32_t g_193_l, int32_t g_194_l, int32_t g_195_l, int32_t g_203_l, char g_237_l, int32_t g_273_l, int16_t g_274_l, int32_t g_291_l, int32_t g_297_l, char g_298_l) {
    // 0x2a40
    *(char *)&g2 = g_8_l;
    *(char *)&g3 = g_9_l;
    g4 = g_29_l;
    g5 = g_31_l;
    g6 = g_35_l;
    g7 = g_47_l;
    g8 = g_48_l;
    *(char *)&g9 = g_49_l;
    *(char *)&g10 = g_70_l;
    *(char *)&g11 = g_71_l;
    *(int16_t *)&g12 = g_90_l;
    g13 = g_106_l;
    *(char *)&g14 = g_107_l;
    g15 = g_108_l;
    g16 = g_109_l;
    *(char *)&g17 = g_111_l;
    g18 = g_191_l;
    g19 = g_192_l;
    g20 = g_193_l;
    g21 = g_194_l;
    g22 = g_195_l;
    g23 = g_203_l;
    *(char *)&g29 = g_237_l;
    g24 = g_273_l;
    g30 = g_274_l;
    g25 = g_291_l;
    g31 = g_297_l;
    *(char *)&g26 = g_298_l;
    return 0;
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2bf0 - 0x2c4d
// Line range:    85 - 91
void crc32_8bytes(uint32_t val) {
    // 0x2bf0
    crc32_byte((char)val);
    crc32_byte((char)(val / 256));
    crc32_byte((char)(val / 0x10000));
    crc32_byte((char)(val / 0x1000000));
}

// From module:   /home/weicheng/Documents/CS699_WASM/DecFuzzer/./seed_all/stdint-uintn.h
// Address range: 0x2c50 - 0x2c90
// Line range:    77 - 81
void crc32_byte(unsigned char b) {
    uint32_t v1 = g27;
    int32_t v2 = *(int32_t *)((int64_t)(4 * (v1 % 256 ^ (int32_t)b)) + (int64_t)&g32); // 0x2c85
    g27 = v1 / 256 ^ v2;
}

// Address range: 0x2c90 - 0x2c9d
int64_t _fini(void) {
    // 0x2c90
    int64_t result; // 0x2c90
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: llvm (15.0.7)
// Detected functions: 18

